/*
 * Snowflake SQL API
 * The Snowflake SQL API is a REST API that you can use to access and update data in a Snowflake database. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.api;

import eu.openanalytics.containerproxy.backend.spcs.client.ApiCallback;
import eu.openanalytics.containerproxy.backend.spcs.client.ApiClient;
import eu.openanalytics.containerproxy.backend.spcs.client.ApiException;
import eu.openanalytics.containerproxy.backend.spcs.client.ApiResponse;
import eu.openanalytics.containerproxy.backend.spcs.client.Configuration;
import eu.openanalytics.containerproxy.backend.spcs.client.Pair;
import eu.openanalytics.containerproxy.backend.spcs.client.ProgressRequestBody;
import eu.openanalytics.containerproxy.backend.spcs.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import eu.openanalytics.containerproxy.backend.spcs.client.model.CancelStatus;
import eu.openanalytics.containerproxy.backend.spcs.client.model.QueryFailureStatus;
import eu.openanalytics.containerproxy.backend.spcs.client.model.QueryStatus;
import eu.openanalytics.containerproxy.backend.spcs.client.model.ResultSet;
import eu.openanalytics.containerproxy.backend.spcs.client.model.SubmitStatementRequest;
import java.util.UUID;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class StatementsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public StatementsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public StatementsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for cancelStatement
     * @param statementHandle The handle of the statement that you want to use (e.g. to fetch the result set or cancel execution). (required)
     * @param userAgent Set this to the name and version of your application (e.g. “applicationName/applicationVersion”). You must use a value that complies with RFC 7231. (required)
     * @param requestId Unique ID of the API request. This ensures that the execution is idempotent. If not specified, a new UUID is generated and assigned. (optional)
     * @param accept The response payload format. The schema should be specified in resultSetMetaData in the request payload. (optional)
     * @param xSnowflakeAuthorizationTokenType Specify the authorization token type for the Authorization header. KEYPAIR_JWT is for Keypair JWT or OAUTH for oAuth token. If not specified, OAUTH is assumed. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The execution of the statement was successfully canceled. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request payload is invalid or malformed. This happens if the application didn&#39;t send the correct request payload. The response body may include the error code and message indicating the actual cause. The application must reconstruct the request body for retry. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request is not authorized. This happens if the attached access token is invalid or missing. The response body may include the error code and message indicating the actual cause, e.g., expired, invalid token. The application must obtain a new access token for retry. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request is forbidden. This happens if the request is made even if the API is not enabled. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found. The request endpoint is not valid. This happens if the API endpoint is wrong. For example, if the application hits /api/api/hello which doesn&#39;t exist, it will receive this code. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Method Not Allowed. The request method doesn&#39;t match the supported API. This happens, for example, if the application calls the API with GET method but the endpoint accepts only POST. The application must change a method for retry. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> An error occurred when cancelling the execution of the statement. Check the error code and error message for details. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error. The server hits an unrecoverable system error. The response body may include the error code and message for further guidance. The application owner may need to reach out the customer support. </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> Service Unavailable. The request was not processed due to server side timeouts. The application may retry with backoff. The jittered backoff is recommended. https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/ </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> Gateway Timeout. The request was not processed due to server side timeouts. The application may retry with backoff. The jittered backoff is recommended. https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/ </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call cancelStatementCall(@javax.annotation.Nonnull UUID statementHandle, @javax.annotation.Nonnull String userAgent, @javax.annotation.Nullable UUID requestId, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String xSnowflakeAuthorizationTokenType, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v2/statements/{statementHandle}/cancel"
            .replace("{" + "statementHandle" + "}", localVarApiClient.escapeString(statementHandle.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (requestId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("requestId", requestId));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (accept != null) {
            localVarHeaderParams.put("Accept", localVarApiClient.parameterToString(accept));
        }


        if (userAgent != null) {
            localVarHeaderParams.put("User-Agent", localVarApiClient.parameterToString(userAgent));
        }


        if (xSnowflakeAuthorizationTokenType != null) {
            localVarHeaderParams.put("X-Snowflake-Authorization-Token-Type", localVarApiClient.parameterToString(xSnowflakeAuthorizationTokenType));
        }


        // BUG in auto generated code: "snowflakeOAuth" should be "SnowflakeOAuth", "keyPair" should be "KeyPair"
        String[] localVarAuthNames = new String[] { "ExternalOAuth", "SnowflakeOAuth", "KeyPair" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call cancelStatementValidateBeforeCall(@javax.annotation.Nonnull UUID statementHandle, @javax.annotation.Nonnull String userAgent, @javax.annotation.Nullable UUID requestId, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String xSnowflakeAuthorizationTokenType, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'statementHandle' is set
        if (statementHandle == null) {
            throw new ApiException("Missing the required parameter 'statementHandle' when calling cancelStatement(Async)");
        }

        // verify the required parameter 'userAgent' is set
        if (userAgent == null) {
            throw new ApiException("Missing the required parameter 'userAgent' when calling cancelStatement(Async)");
        }

        return cancelStatementCall(statementHandle, userAgent, requestId, accept, xSnowflakeAuthorizationTokenType, _callback);

    }

    /**
     * Cancels the execution of a statement.
     * Cancels the execution of the statement with the specified statement handle.
     * @param statementHandle The handle of the statement that you want to use (e.g. to fetch the result set or cancel execution). (required)
     * @param userAgent Set this to the name and version of your application (e.g. “applicationName/applicationVersion”). You must use a value that complies with RFC 7231. (required)
     * @param requestId Unique ID of the API request. This ensures that the execution is idempotent. If not specified, a new UUID is generated and assigned. (optional)
     * @param accept The response payload format. The schema should be specified in resultSetMetaData in the request payload. (optional)
     * @param xSnowflakeAuthorizationTokenType Specify the authorization token type for the Authorization header. KEYPAIR_JWT is for Keypair JWT or OAUTH for oAuth token. If not specified, OAUTH is assumed. (optional)
     * @return CancelStatus
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The execution of the statement was successfully canceled. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request payload is invalid or malformed. This happens if the application didn&#39;t send the correct request payload. The response body may include the error code and message indicating the actual cause. The application must reconstruct the request body for retry. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request is not authorized. This happens if the attached access token is invalid or missing. The response body may include the error code and message indicating the actual cause, e.g., expired, invalid token. The application must obtain a new access token for retry. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request is forbidden. This happens if the request is made even if the API is not enabled. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found. The request endpoint is not valid. This happens if the API endpoint is wrong. For example, if the application hits /api/api/hello which doesn&#39;t exist, it will receive this code. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Method Not Allowed. The request method doesn&#39;t match the supported API. This happens, for example, if the application calls the API with GET method but the endpoint accepts only POST. The application must change a method for retry. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> An error occurred when cancelling the execution of the statement. Check the error code and error message for details. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error. The server hits an unrecoverable system error. The response body may include the error code and message for further guidance. The application owner may need to reach out the customer support. </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> Service Unavailable. The request was not processed due to server side timeouts. The application may retry with backoff. The jittered backoff is recommended. https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/ </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> Gateway Timeout. The request was not processed due to server side timeouts. The application may retry with backoff. The jittered backoff is recommended. https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/ </td><td>  -  </td></tr>
     </table>
     */
    public CancelStatus cancelStatement(@javax.annotation.Nonnull UUID statementHandle, @javax.annotation.Nonnull String userAgent, @javax.annotation.Nullable UUID requestId, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String xSnowflakeAuthorizationTokenType) throws ApiException {
        ApiResponse<CancelStatus> localVarResp = cancelStatementWithHttpInfo(statementHandle, userAgent, requestId, accept, xSnowflakeAuthorizationTokenType);
        return localVarResp.getData();
    }

    /**
     * Cancels the execution of a statement.
     * Cancels the execution of the statement with the specified statement handle.
     * @param statementHandle The handle of the statement that you want to use (e.g. to fetch the result set or cancel execution). (required)
     * @param userAgent Set this to the name and version of your application (e.g. “applicationName/applicationVersion”). You must use a value that complies with RFC 7231. (required)
     * @param requestId Unique ID of the API request. This ensures that the execution is idempotent. If not specified, a new UUID is generated and assigned. (optional)
     * @param accept The response payload format. The schema should be specified in resultSetMetaData in the request payload. (optional)
     * @param xSnowflakeAuthorizationTokenType Specify the authorization token type for the Authorization header. KEYPAIR_JWT is for Keypair JWT or OAUTH for oAuth token. If not specified, OAUTH is assumed. (optional)
     * @return ApiResponse&lt;CancelStatus&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The execution of the statement was successfully canceled. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request payload is invalid or malformed. This happens if the application didn&#39;t send the correct request payload. The response body may include the error code and message indicating the actual cause. The application must reconstruct the request body for retry. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request is not authorized. This happens if the attached access token is invalid or missing. The response body may include the error code and message indicating the actual cause, e.g., expired, invalid token. The application must obtain a new access token for retry. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request is forbidden. This happens if the request is made even if the API is not enabled. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found. The request endpoint is not valid. This happens if the API endpoint is wrong. For example, if the application hits /api/api/hello which doesn&#39;t exist, it will receive this code. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Method Not Allowed. The request method doesn&#39;t match the supported API. This happens, for example, if the application calls the API with GET method but the endpoint accepts only POST. The application must change a method for retry. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> An error occurred when cancelling the execution of the statement. Check the error code and error message for details. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error. The server hits an unrecoverable system error. The response body may include the error code and message for further guidance. The application owner may need to reach out the customer support. </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> Service Unavailable. The request was not processed due to server side timeouts. The application may retry with backoff. The jittered backoff is recommended. https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/ </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> Gateway Timeout. The request was not processed due to server side timeouts. The application may retry with backoff. The jittered backoff is recommended. https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/ </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CancelStatus> cancelStatementWithHttpInfo(@javax.annotation.Nonnull UUID statementHandle, @javax.annotation.Nonnull String userAgent, @javax.annotation.Nullable UUID requestId, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String xSnowflakeAuthorizationTokenType) throws ApiException {
        okhttp3.Call localVarCall = cancelStatementValidateBeforeCall(statementHandle, userAgent, requestId, accept, xSnowflakeAuthorizationTokenType, null);
        Type localVarReturnType = new TypeToken<CancelStatus>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Cancels the execution of a statement. (asynchronously)
     * Cancels the execution of the statement with the specified statement handle.
     * @param statementHandle The handle of the statement that you want to use (e.g. to fetch the result set or cancel execution). (required)
     * @param userAgent Set this to the name and version of your application (e.g. “applicationName/applicationVersion”). You must use a value that complies with RFC 7231. (required)
     * @param requestId Unique ID of the API request. This ensures that the execution is idempotent. If not specified, a new UUID is generated and assigned. (optional)
     * @param accept The response payload format. The schema should be specified in resultSetMetaData in the request payload. (optional)
     * @param xSnowflakeAuthorizationTokenType Specify the authorization token type for the Authorization header. KEYPAIR_JWT is for Keypair JWT or OAUTH for oAuth token. If not specified, OAUTH is assumed. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The execution of the statement was successfully canceled. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request payload is invalid or malformed. This happens if the application didn&#39;t send the correct request payload. The response body may include the error code and message indicating the actual cause. The application must reconstruct the request body for retry. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request is not authorized. This happens if the attached access token is invalid or missing. The response body may include the error code and message indicating the actual cause, e.g., expired, invalid token. The application must obtain a new access token for retry. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request is forbidden. This happens if the request is made even if the API is not enabled. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found. The request endpoint is not valid. This happens if the API endpoint is wrong. For example, if the application hits /api/api/hello which doesn&#39;t exist, it will receive this code. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Method Not Allowed. The request method doesn&#39;t match the supported API. This happens, for example, if the application calls the API with GET method but the endpoint accepts only POST. The application must change a method for retry. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> An error occurred when cancelling the execution of the statement. Check the error code and error message for details. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error. The server hits an unrecoverable system error. The response body may include the error code and message for further guidance. The application owner may need to reach out the customer support. </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> Service Unavailable. The request was not processed due to server side timeouts. The application may retry with backoff. The jittered backoff is recommended. https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/ </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> Gateway Timeout. The request was not processed due to server side timeouts. The application may retry with backoff. The jittered backoff is recommended. https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/ </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call cancelStatementAsync(@javax.annotation.Nonnull UUID statementHandle, @javax.annotation.Nonnull String userAgent, @javax.annotation.Nullable UUID requestId, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String xSnowflakeAuthorizationTokenType, final ApiCallback<CancelStatus> _callback) throws ApiException {

        okhttp3.Call localVarCall = cancelStatementValidateBeforeCall(statementHandle, userAgent, requestId, accept, xSnowflakeAuthorizationTokenType, _callback);
        Type localVarReturnType = new TypeToken<CancelStatus>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getStatementStatus
     * @param statementHandle The handle of the statement that you want to use (e.g. to fetch the result set or cancel execution). (required)
     * @param userAgent Set this to the name and version of your application (e.g. “applicationName/applicationVersion”). You must use a value that complies with RFC 7231. (required)
     * @param requestId Unique ID of the API request. This ensures that the execution is idempotent. If not specified, a new UUID is generated and assigned. (optional)
     * @param partition Number of the partition of results to return. The number can range from 0 to the total number of partitions minus 1. (optional)
     * @param accept The response payload format. The schema should be specified in resultSetMetaData in the request payload. (optional)
     * @param xSnowflakeAuthorizationTokenType Specify the authorization token type for the Authorization header. KEYPAIR_JWT is for Keypair JWT or OAUTH for oAuth token. If not specified, OAUTH is assumed. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The statement was executed successfully, and the response includes any data requested. </td><td>  * link -  <br>  </td></tr>
        <tr><td> 202 </td><td> The execution of the statement is still in progress. Use this method again to check the status of the statement execution. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request payload is invalid or malformed. This happens if the application didn&#39;t send the correct request payload. The response body may include the error code and message indicating the actual cause. The application must reconstruct the request body for retry. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request is not authorized. This happens if the attached access token is invalid or missing. The response body may include the error code and message indicating the actual cause, e.g., expired, invalid token. The application must obtain a new access token for retry. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request is forbidden. This happens if the request is made even if the API is not enabled. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found. The request endpoint is not valid. This happens if the API endpoint is wrong. For example, if the application hits /api/api/hello which doesn&#39;t exist, it will receive this code. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Method Not Allowed. The request method doesn&#39;t match the supported API. This happens, for example, if the application calls the API with GET method but the endpoint accepts only POST. The application must change a method for retry. </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> The request header Content-Type includes unsupported media type. The API supports application/json only. If none specified, the request payload is taken as JSON, but if any other media type is specified, this error is returned. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> An error occurred when executing the statement. Check the error code and error message for details. </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Limit Exceeded. The number of requests hit the rate limit. The application must slow down the frequency of hitting the API endpoints. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error. The server hits an unrecoverable system error. The response body may include the error code and message for further guidance. The application owner may need to reach out the customer support. </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> Service Unavailable. The request was not processed due to server side timeouts. The application may retry with backoff. The jittered backoff is recommended. https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/ </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> Gateway Timeout. The request was not processed due to server side timeouts. The application may retry with backoff. The jittered backoff is recommended. https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/ </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getStatementStatusCall(@javax.annotation.Nonnull UUID statementHandle, @javax.annotation.Nonnull String userAgent, @javax.annotation.Nullable UUID requestId, @javax.annotation.Nullable Long partition, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String xSnowflakeAuthorizationTokenType, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v2/statements/{statementHandle}"
            .replace("{" + "statementHandle" + "}", localVarApiClient.escapeString(statementHandle.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (requestId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("requestId", requestId));
        }

        if (partition != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("partition", partition));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (accept != null) {
            localVarHeaderParams.put("Accept", localVarApiClient.parameterToString(accept));
        }


        if (userAgent != null) {
            localVarHeaderParams.put("User-Agent", localVarApiClient.parameterToString(userAgent));
        }


        if (xSnowflakeAuthorizationTokenType != null) {
            localVarHeaderParams.put("X-Snowflake-Authorization-Token-Type", localVarApiClient.parameterToString(xSnowflakeAuthorizationTokenType));
        }


        // BUG in auto generated code: "snowflakeOAuth" should be "SnowflakeOAuth", "keyPair" should be "KeyPair"
        String[] localVarAuthNames = new String[] { "ExternalOAuth", "SnowflakeOAuth", "KeyPair" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getStatementStatusValidateBeforeCall(@javax.annotation.Nonnull UUID statementHandle, @javax.annotation.Nonnull String userAgent, @javax.annotation.Nullable UUID requestId, @javax.annotation.Nullable Long partition, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String xSnowflakeAuthorizationTokenType, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'statementHandle' is set
        if (statementHandle == null) {
            throw new ApiException("Missing the required parameter 'statementHandle' when calling getStatementStatus(Async)");
        }

        // verify the required parameter 'userAgent' is set
        if (userAgent == null) {
            throw new ApiException("Missing the required parameter 'userAgent' when calling getStatementStatus(Async)");
        }

        return getStatementStatusCall(statementHandle, userAgent, requestId, partition, accept, xSnowflakeAuthorizationTokenType, _callback);

    }

    /**
     * Checks the status of the execution of a statement
     * Checks the status of the execution of the statement with the specified statement handle. If the statement was executed successfully, the operation returns the requested partition of the result set.
     * @param statementHandle The handle of the statement that you want to use (e.g. to fetch the result set or cancel execution). (required)
     * @param userAgent Set this to the name and version of your application (e.g. “applicationName/applicationVersion”). You must use a value that complies with RFC 7231. (required)
     * @param requestId Unique ID of the API request. This ensures that the execution is idempotent. If not specified, a new UUID is generated and assigned. (optional)
     * @param partition Number of the partition of results to return. The number can range from 0 to the total number of partitions minus 1. (optional)
     * @param accept The response payload format. The schema should be specified in resultSetMetaData in the request payload. (optional)
     * @param xSnowflakeAuthorizationTokenType Specify the authorization token type for the Authorization header. KEYPAIR_JWT is for Keypair JWT or OAUTH for oAuth token. If not specified, OAUTH is assumed. (optional)
     * @return ResultSet
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The statement was executed successfully, and the response includes any data requested. </td><td>  * link -  <br>  </td></tr>
        <tr><td> 202 </td><td> The execution of the statement is still in progress. Use this method again to check the status of the statement execution. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request payload is invalid or malformed. This happens if the application didn&#39;t send the correct request payload. The response body may include the error code and message indicating the actual cause. The application must reconstruct the request body for retry. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request is not authorized. This happens if the attached access token is invalid or missing. The response body may include the error code and message indicating the actual cause, e.g., expired, invalid token. The application must obtain a new access token for retry. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request is forbidden. This happens if the request is made even if the API is not enabled. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found. The request endpoint is not valid. This happens if the API endpoint is wrong. For example, if the application hits /api/api/hello which doesn&#39;t exist, it will receive this code. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Method Not Allowed. The request method doesn&#39;t match the supported API. This happens, for example, if the application calls the API with GET method but the endpoint accepts only POST. The application must change a method for retry. </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> The request header Content-Type includes unsupported media type. The API supports application/json only. If none specified, the request payload is taken as JSON, but if any other media type is specified, this error is returned. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> An error occurred when executing the statement. Check the error code and error message for details. </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Limit Exceeded. The number of requests hit the rate limit. The application must slow down the frequency of hitting the API endpoints. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error. The server hits an unrecoverable system error. The response body may include the error code and message for further guidance. The application owner may need to reach out the customer support. </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> Service Unavailable. The request was not processed due to server side timeouts. The application may retry with backoff. The jittered backoff is recommended. https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/ </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> Gateway Timeout. The request was not processed due to server side timeouts. The application may retry with backoff. The jittered backoff is recommended. https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/ </td><td>  -  </td></tr>
     </table>
     */
    public ResultSet getStatementStatus(@javax.annotation.Nonnull UUID statementHandle, @javax.annotation.Nonnull String userAgent, @javax.annotation.Nullable UUID requestId, @javax.annotation.Nullable Long partition, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String xSnowflakeAuthorizationTokenType) throws ApiException {
        ApiResponse<ResultSet> localVarResp = getStatementStatusWithHttpInfo(statementHandle, userAgent, requestId, partition, accept, xSnowflakeAuthorizationTokenType);
        return localVarResp.getData();
    }

    /**
     * Checks the status of the execution of a statement
     * Checks the status of the execution of the statement with the specified statement handle. If the statement was executed successfully, the operation returns the requested partition of the result set.
     * @param statementHandle The handle of the statement that you want to use (e.g. to fetch the result set or cancel execution). (required)
     * @param userAgent Set this to the name and version of your application (e.g. “applicationName/applicationVersion”). You must use a value that complies with RFC 7231. (required)
     * @param requestId Unique ID of the API request. This ensures that the execution is idempotent. If not specified, a new UUID is generated and assigned. (optional)
     * @param partition Number of the partition of results to return. The number can range from 0 to the total number of partitions minus 1. (optional)
     * @param accept The response payload format. The schema should be specified in resultSetMetaData in the request payload. (optional)
     * @param xSnowflakeAuthorizationTokenType Specify the authorization token type for the Authorization header. KEYPAIR_JWT is for Keypair JWT or OAUTH for oAuth token. If not specified, OAUTH is assumed. (optional)
     * @return ApiResponse&lt;ResultSet&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The statement was executed successfully, and the response includes any data requested. </td><td>  * link -  <br>  </td></tr>
        <tr><td> 202 </td><td> The execution of the statement is still in progress. Use this method again to check the status of the statement execution. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request payload is invalid or malformed. This happens if the application didn&#39;t send the correct request payload. The response body may include the error code and message indicating the actual cause. The application must reconstruct the request body for retry. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request is not authorized. This happens if the attached access token is invalid or missing. The response body may include the error code and message indicating the actual cause, e.g., expired, invalid token. The application must obtain a new access token for retry. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request is forbidden. This happens if the request is made even if the API is not enabled. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found. The request endpoint is not valid. This happens if the API endpoint is wrong. For example, if the application hits /api/api/hello which doesn&#39;t exist, it will receive this code. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Method Not Allowed. The request method doesn&#39;t match the supported API. This happens, for example, if the application calls the API with GET method but the endpoint accepts only POST. The application must change a method for retry. </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> The request header Content-Type includes unsupported media type. The API supports application/json only. If none specified, the request payload is taken as JSON, but if any other media type is specified, this error is returned. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> An error occurred when executing the statement. Check the error code and error message for details. </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Limit Exceeded. The number of requests hit the rate limit. The application must slow down the frequency of hitting the API endpoints. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error. The server hits an unrecoverable system error. The response body may include the error code and message for further guidance. The application owner may need to reach out the customer support. </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> Service Unavailable. The request was not processed due to server side timeouts. The application may retry with backoff. The jittered backoff is recommended. https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/ </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> Gateway Timeout. The request was not processed due to server side timeouts. The application may retry with backoff. The jittered backoff is recommended. https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/ </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ResultSet> getStatementStatusWithHttpInfo(@javax.annotation.Nonnull UUID statementHandle, @javax.annotation.Nonnull String userAgent, @javax.annotation.Nullable UUID requestId, @javax.annotation.Nullable Long partition, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String xSnowflakeAuthorizationTokenType) throws ApiException {
        okhttp3.Call localVarCall = getStatementStatusValidateBeforeCall(statementHandle, userAgent, requestId, partition, accept, xSnowflakeAuthorizationTokenType, null);
        Type localVarReturnType = new TypeToken<ResultSet>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Checks the status of the execution of a statement (asynchronously)
     * Checks the status of the execution of the statement with the specified statement handle. If the statement was executed successfully, the operation returns the requested partition of the result set.
     * @param statementHandle The handle of the statement that you want to use (e.g. to fetch the result set or cancel execution). (required)
     * @param userAgent Set this to the name and version of your application (e.g. “applicationName/applicationVersion”). You must use a value that complies with RFC 7231. (required)
     * @param requestId Unique ID of the API request. This ensures that the execution is idempotent. If not specified, a new UUID is generated and assigned. (optional)
     * @param partition Number of the partition of results to return. The number can range from 0 to the total number of partitions minus 1. (optional)
     * @param accept The response payload format. The schema should be specified in resultSetMetaData in the request payload. (optional)
     * @param xSnowflakeAuthorizationTokenType Specify the authorization token type for the Authorization header. KEYPAIR_JWT is for Keypair JWT or OAUTH for oAuth token. If not specified, OAUTH is assumed. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The statement was executed successfully, and the response includes any data requested. </td><td>  * link -  <br>  </td></tr>
        <tr><td> 202 </td><td> The execution of the statement is still in progress. Use this method again to check the status of the statement execution. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request payload is invalid or malformed. This happens if the application didn&#39;t send the correct request payload. The response body may include the error code and message indicating the actual cause. The application must reconstruct the request body for retry. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request is not authorized. This happens if the attached access token is invalid or missing. The response body may include the error code and message indicating the actual cause, e.g., expired, invalid token. The application must obtain a new access token for retry. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request is forbidden. This happens if the request is made even if the API is not enabled. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found. The request endpoint is not valid. This happens if the API endpoint is wrong. For example, if the application hits /api/api/hello which doesn&#39;t exist, it will receive this code. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Method Not Allowed. The request method doesn&#39;t match the supported API. This happens, for example, if the application calls the API with GET method but the endpoint accepts only POST. The application must change a method for retry. </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> The request header Content-Type includes unsupported media type. The API supports application/json only. If none specified, the request payload is taken as JSON, but if any other media type is specified, this error is returned. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> An error occurred when executing the statement. Check the error code and error message for details. </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Limit Exceeded. The number of requests hit the rate limit. The application must slow down the frequency of hitting the API endpoints. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error. The server hits an unrecoverable system error. The response body may include the error code and message for further guidance. The application owner may need to reach out the customer support. </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> Service Unavailable. The request was not processed due to server side timeouts. The application may retry with backoff. The jittered backoff is recommended. https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/ </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> Gateway Timeout. The request was not processed due to server side timeouts. The application may retry with backoff. The jittered backoff is recommended. https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/ </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getStatementStatusAsync(@javax.annotation.Nonnull UUID statementHandle, @javax.annotation.Nonnull String userAgent, @javax.annotation.Nullable UUID requestId, @javax.annotation.Nullable Long partition, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String xSnowflakeAuthorizationTokenType, final ApiCallback<ResultSet> _callback) throws ApiException {

        okhttp3.Call localVarCall = getStatementStatusValidateBeforeCall(statementHandle, userAgent, requestId, partition, accept, xSnowflakeAuthorizationTokenType, _callback);
        Type localVarReturnType = new TypeToken<ResultSet>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for submitStatement
     * @param userAgent Set this to the name and version of your application (e.g. “applicationName/applicationVersion”). You must use a value that complies with RFC 7231. (required)
     * @param submitStatementRequest Specifies the SQL statement to execute and the statement context. (required)
     * @param requestId Unique ID of the API request. This ensures that the execution is idempotent. If not specified, a new UUID is generated and assigned. (optional)
     * @param async Set to true to execute the statement asynchronously and return the statement handle. If the parameter is not specified or is set to false, a statement is executed and the first result is returned if the execution is completed in 45 seconds. If the statement execution takes longer to complete, the statement handle is returned. (optional)
     * @param nullable Set to true to execute the statement to generate the result set including null. If the parameter is set to false, the result set value null will be replaced with a string &#39;null&#39;. (optional)
     * @param accept The response payload format. The schema should be specified in resultSetMetaData in the request payload. (optional)
     * @param xSnowflakeAuthorizationTokenType Specify the authorization token type for the Authorization header. KEYPAIR_JWT is for Keypair JWT or OAUTH for oAuth token. If not specified, OAUTH is assumed. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The statement was executed successfully, and the response includes any data requested. </td><td>  * link -  <br>  </td></tr>
        <tr><td> 202 </td><td> The execution of the statement is still in progress. Use GET /statements/ and specify the statement handle to check the status of the statement execution. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request payload is invalid or malformed. This happens if the application didn&#39;t send the correct request payload. The response body may include the error code and message indicating the actual cause. The application must reconstruct the request body for retry. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request is not authorized. This happens if the attached access token is invalid or missing. The response body may include the error code and message indicating the actual cause, e.g., expired, invalid token. The application must obtain a new access token for retry. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request is forbidden. This happens if the request is made even if the API is not enabled. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found. The request endpoint is not valid. This happens if the API endpoint is wrong. For example, if the application hits /api/api/hello which doesn&#39;t exist, it will receive this code. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Method Not Allowed. The request method doesn&#39;t match the supported API. This happens, for example, if the application calls the API with GET method but the endpoint accepts only POST. The application must change a method for retry. </td><td>  -  </td></tr>
        <tr><td> 408 </td><td> The execution of the statement exceeded the timeout period. The execution of the statement was cancelled. </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> The request header Content-Type includes unsupported media type. The API supports application/json only. If none specified, the request payload is taken as JSON, but if any other media type is specified, this error is returned. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> An error occurred when executing the statement. Check the error code and error message for details. </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Limit Exceeded. The number of requests hit the rate limit. The application must slow down the frequency of hitting the API endpoints. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error. The server hits an unrecoverable system error. The response body may include the error code and message for further guidance. The application owner may need to reach out the customer support. </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> Service Unavailable. The request was not processed due to server side timeouts. The application may retry with backoff. The jittered backoff is recommended. https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/ </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> Gateway Timeout. The request was not processed due to server side timeouts. The application may retry with backoff. The jittered backoff is recommended. https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/ </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call submitStatementCall(@javax.annotation.Nonnull String userAgent, @javax.annotation.Nonnull SubmitStatementRequest submitStatementRequest, @javax.annotation.Nullable UUID requestId, @javax.annotation.Nullable Boolean async, @javax.annotation.Nullable Boolean nullable, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String xSnowflakeAuthorizationTokenType, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = submitStatementRequest;

        // create path and map variables
        String localVarPath = "/api/v2/statements";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (requestId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("requestId", requestId));
        }

        if (async != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("async", async));
        }

        if (nullable != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("nullable", nullable));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (accept != null) {
            localVarHeaderParams.put("Accept", localVarApiClient.parameterToString(accept));
        }


        if (userAgent != null) {
            localVarHeaderParams.put("User-Agent", localVarApiClient.parameterToString(userAgent));
        }


        if (xSnowflakeAuthorizationTokenType != null) {
            localVarHeaderParams.put("X-Snowflake-Authorization-Token-Type", localVarApiClient.parameterToString(xSnowflakeAuthorizationTokenType));
        }


        // BUG in auto generated code: "snowflakeOAuth" should be "SnowflakeOAuth", "keyPair" should be "KeyPair"
        String[] localVarAuthNames = new String[] { "ExternalOAuth", "SnowflakeOAuth", "KeyPair" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call submitStatementValidateBeforeCall(@javax.annotation.Nonnull String userAgent, @javax.annotation.Nonnull SubmitStatementRequest submitStatementRequest, @javax.annotation.Nullable UUID requestId, @javax.annotation.Nullable Boolean async, @javax.annotation.Nullable Boolean nullable, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String xSnowflakeAuthorizationTokenType, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'userAgent' is set
        if (userAgent == null) {
            throw new ApiException("Missing the required parameter 'userAgent' when calling submitStatement(Async)");
        }

        // verify the required parameter 'submitStatementRequest' is set
        if (submitStatementRequest == null) {
            throw new ApiException("Missing the required parameter 'submitStatementRequest' when calling submitStatement(Async)");
        }

        return submitStatementCall(userAgent, submitStatementRequest, requestId, async, nullable, accept, xSnowflakeAuthorizationTokenType, _callback);

    }

    /**
     * Submits a SQL statement for execution.
     * Submits one or more statements for execution. You can specify that the statement should be executed asynchronously.
     * @param userAgent Set this to the name and version of your application (e.g. “applicationName/applicationVersion”). You must use a value that complies with RFC 7231. (required)
     * @param submitStatementRequest Specifies the SQL statement to execute and the statement context. (required)
     * @param requestId Unique ID of the API request. This ensures that the execution is idempotent. If not specified, a new UUID is generated and assigned. (optional)
     * @param async Set to true to execute the statement asynchronously and return the statement handle. If the parameter is not specified or is set to false, a statement is executed and the first result is returned if the execution is completed in 45 seconds. If the statement execution takes longer to complete, the statement handle is returned. (optional)
     * @param nullable Set to true to execute the statement to generate the result set including null. If the parameter is set to false, the result set value null will be replaced with a string &#39;null&#39;. (optional)
     * @param accept The response payload format. The schema should be specified in resultSetMetaData in the request payload. (optional)
     * @param xSnowflakeAuthorizationTokenType Specify the authorization token type for the Authorization header. KEYPAIR_JWT is for Keypair JWT or OAUTH for oAuth token. If not specified, OAUTH is assumed. (optional)
     * @return ResultSet
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The statement was executed successfully, and the response includes any data requested. </td><td>  * link -  <br>  </td></tr>
        <tr><td> 202 </td><td> The execution of the statement is still in progress. Use GET /statements/ and specify the statement handle to check the status of the statement execution. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request payload is invalid or malformed. This happens if the application didn&#39;t send the correct request payload. The response body may include the error code and message indicating the actual cause. The application must reconstruct the request body for retry. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request is not authorized. This happens if the attached access token is invalid or missing. The response body may include the error code and message indicating the actual cause, e.g., expired, invalid token. The application must obtain a new access token for retry. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request is forbidden. This happens if the request is made even if the API is not enabled. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found. The request endpoint is not valid. This happens if the API endpoint is wrong. For example, if the application hits /api/api/hello which doesn&#39;t exist, it will receive this code. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Method Not Allowed. The request method doesn&#39;t match the supported API. This happens, for example, if the application calls the API with GET method but the endpoint accepts only POST. The application must change a method for retry. </td><td>  -  </td></tr>
        <tr><td> 408 </td><td> The execution of the statement exceeded the timeout period. The execution of the statement was cancelled. </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> The request header Content-Type includes unsupported media type. The API supports application/json only. If none specified, the request payload is taken as JSON, but if any other media type is specified, this error is returned. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> An error occurred when executing the statement. Check the error code and error message for details. </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Limit Exceeded. The number of requests hit the rate limit. The application must slow down the frequency of hitting the API endpoints. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error. The server hits an unrecoverable system error. The response body may include the error code and message for further guidance. The application owner may need to reach out the customer support. </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> Service Unavailable. The request was not processed due to server side timeouts. The application may retry with backoff. The jittered backoff is recommended. https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/ </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> Gateway Timeout. The request was not processed due to server side timeouts. The application may retry with backoff. The jittered backoff is recommended. https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/ </td><td>  -  </td></tr>
     </table>
     */
    public ResultSet submitStatement(@javax.annotation.Nonnull String userAgent, @javax.annotation.Nonnull SubmitStatementRequest submitStatementRequest, @javax.annotation.Nullable UUID requestId, @javax.annotation.Nullable Boolean async, @javax.annotation.Nullable Boolean nullable, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String xSnowflakeAuthorizationTokenType) throws ApiException {
        ApiResponse<ResultSet> localVarResp = submitStatementWithHttpInfo(userAgent, submitStatementRequest, requestId, async, nullable, accept, xSnowflakeAuthorizationTokenType);
        return localVarResp.getData();
    }

    /**
     * Submits a SQL statement for execution.
     * Submits one or more statements for execution. You can specify that the statement should be executed asynchronously.
     * @param userAgent Set this to the name and version of your application (e.g. “applicationName/applicationVersion”). You must use a value that complies with RFC 7231. (required)
     * @param submitStatementRequest Specifies the SQL statement to execute and the statement context. (required)
     * @param requestId Unique ID of the API request. This ensures that the execution is idempotent. If not specified, a new UUID is generated and assigned. (optional)
     * @param async Set to true to execute the statement asynchronously and return the statement handle. If the parameter is not specified or is set to false, a statement is executed and the first result is returned if the execution is completed in 45 seconds. If the statement execution takes longer to complete, the statement handle is returned. (optional)
     * @param nullable Set to true to execute the statement to generate the result set including null. If the parameter is set to false, the result set value null will be replaced with a string &#39;null&#39;. (optional)
     * @param accept The response payload format. The schema should be specified in resultSetMetaData in the request payload. (optional)
     * @param xSnowflakeAuthorizationTokenType Specify the authorization token type for the Authorization header. KEYPAIR_JWT is for Keypair JWT or OAUTH for oAuth token. If not specified, OAUTH is assumed. (optional)
     * @return ApiResponse&lt;ResultSet&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The statement was executed successfully, and the response includes any data requested. </td><td>  * link -  <br>  </td></tr>
        <tr><td> 202 </td><td> The execution of the statement is still in progress. Use GET /statements/ and specify the statement handle to check the status of the statement execution. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request payload is invalid or malformed. This happens if the application didn&#39;t send the correct request payload. The response body may include the error code and message indicating the actual cause. The application must reconstruct the request body for retry. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request is not authorized. This happens if the attached access token is invalid or missing. The response body may include the error code and message indicating the actual cause, e.g., expired, invalid token. The application must obtain a new access token for retry. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request is forbidden. This happens if the request is made even if the API is not enabled. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found. The request endpoint is not valid. This happens if the API endpoint is wrong. For example, if the application hits /api/api/hello which doesn&#39;t exist, it will receive this code. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Method Not Allowed. The request method doesn&#39;t match the supported API. This happens, for example, if the application calls the API with GET method but the endpoint accepts only POST. The application must change a method for retry. </td><td>  -  </td></tr>
        <tr><td> 408 </td><td> The execution of the statement exceeded the timeout period. The execution of the statement was cancelled. </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> The request header Content-Type includes unsupported media type. The API supports application/json only. If none specified, the request payload is taken as JSON, but if any other media type is specified, this error is returned. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> An error occurred when executing the statement. Check the error code and error message for details. </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Limit Exceeded. The number of requests hit the rate limit. The application must slow down the frequency of hitting the API endpoints. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error. The server hits an unrecoverable system error. The response body may include the error code and message for further guidance. The application owner may need to reach out the customer support. </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> Service Unavailable. The request was not processed due to server side timeouts. The application may retry with backoff. The jittered backoff is recommended. https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/ </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> Gateway Timeout. The request was not processed due to server side timeouts. The application may retry with backoff. The jittered backoff is recommended. https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/ </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ResultSet> submitStatementWithHttpInfo(@javax.annotation.Nonnull String userAgent, @javax.annotation.Nonnull SubmitStatementRequest submitStatementRequest, @javax.annotation.Nullable UUID requestId, @javax.annotation.Nullable Boolean async, @javax.annotation.Nullable Boolean nullable, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String xSnowflakeAuthorizationTokenType) throws ApiException {
        okhttp3.Call localVarCall = submitStatementValidateBeforeCall(userAgent, submitStatementRequest, requestId, async, nullable, accept, xSnowflakeAuthorizationTokenType, null);
        Type localVarReturnType = new TypeToken<ResultSet>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Submits a SQL statement for execution. (asynchronously)
     * Submits one or more statements for execution. You can specify that the statement should be executed asynchronously.
     * @param userAgent Set this to the name and version of your application (e.g. “applicationName/applicationVersion”). You must use a value that complies with RFC 7231. (required)
     * @param submitStatementRequest Specifies the SQL statement to execute and the statement context. (required)
     * @param requestId Unique ID of the API request. This ensures that the execution is idempotent. If not specified, a new UUID is generated and assigned. (optional)
     * @param async Set to true to execute the statement asynchronously and return the statement handle. If the parameter is not specified or is set to false, a statement is executed and the first result is returned if the execution is completed in 45 seconds. If the statement execution takes longer to complete, the statement handle is returned. (optional)
     * @param nullable Set to true to execute the statement to generate the result set including null. If the parameter is set to false, the result set value null will be replaced with a string &#39;null&#39;. (optional)
     * @param accept The response payload format. The schema should be specified in resultSetMetaData in the request payload. (optional)
     * @param xSnowflakeAuthorizationTokenType Specify the authorization token type for the Authorization header. KEYPAIR_JWT is for Keypair JWT or OAUTH for oAuth token. If not specified, OAUTH is assumed. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The statement was executed successfully, and the response includes any data requested. </td><td>  * link -  <br>  </td></tr>
        <tr><td> 202 </td><td> The execution of the statement is still in progress. Use GET /statements/ and specify the statement handle to check the status of the statement execution. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request payload is invalid or malformed. This happens if the application didn&#39;t send the correct request payload. The response body may include the error code and message indicating the actual cause. The application must reconstruct the request body for retry. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request is not authorized. This happens if the attached access token is invalid or missing. The response body may include the error code and message indicating the actual cause, e.g., expired, invalid token. The application must obtain a new access token for retry. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request is forbidden. This happens if the request is made even if the API is not enabled. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not Found. The request endpoint is not valid. This happens if the API endpoint is wrong. For example, if the application hits /api/api/hello which doesn&#39;t exist, it will receive this code. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Method Not Allowed. The request method doesn&#39;t match the supported API. This happens, for example, if the application calls the API with GET method but the endpoint accepts only POST. The application must change a method for retry. </td><td>  -  </td></tr>
        <tr><td> 408 </td><td> The execution of the statement exceeded the timeout period. The execution of the statement was cancelled. </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> The request header Content-Type includes unsupported media type. The API supports application/json only. If none specified, the request payload is taken as JSON, but if any other media type is specified, this error is returned. </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> An error occurred when executing the statement. Check the error code and error message for details. </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Limit Exceeded. The number of requests hit the rate limit. The application must slow down the frequency of hitting the API endpoints. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error. The server hits an unrecoverable system error. The response body may include the error code and message for further guidance. The application owner may need to reach out the customer support. </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> Service Unavailable. The request was not processed due to server side timeouts. The application may retry with backoff. The jittered backoff is recommended. https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/ </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> Gateway Timeout. The request was not processed due to server side timeouts. The application may retry with backoff. The jittered backoff is recommended. https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/ </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call submitStatementAsync(@javax.annotation.Nonnull String userAgent, @javax.annotation.Nonnull SubmitStatementRequest submitStatementRequest, @javax.annotation.Nullable UUID requestId, @javax.annotation.Nullable Boolean async, @javax.annotation.Nullable Boolean nullable, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String xSnowflakeAuthorizationTokenType, final ApiCallback<ResultSet> _callback) throws ApiException {

        okhttp3.Call localVarCall = submitStatementValidateBeforeCall(userAgent, submitStatementRequest, requestId, async, nullable, accept, xSnowflakeAuthorizationTokenType, _callback);
        Type localVarReturnType = new TypeToken<ResultSet>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
