/*
 * Snowflake Services API
 * The Snowflake Services API is a REST API that you can use to access, update, and perform certain actions on Services resource in a Snowflake database.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import eu.openanalytics.containerproxy.backend.spcs.client.JSON;

/**
 * FetchServiceLogs200Response
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-06T17:47:48.337179400+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
public class FetchServiceLogs200Response {
  public static final String SERIALIZED_NAME_SYSTEM$GET_SERVICE_LOGS = "system$get_service_logs";
  @SerializedName(SERIALIZED_NAME_SYSTEM$GET_SERVICE_LOGS)
  @javax.annotation.Nullable
  private String system$getServiceLogs;

  public FetchServiceLogs200Response() {
  }

  public FetchServiceLogs200Response system$getServiceLogs(@javax.annotation.Nullable String system$getServiceLogs) {
    this.system$getServiceLogs = system$getServiceLogs;
    return this;
  }

  /**
   * Get system$getServiceLogs
   * @return system$getServiceLogs
   */
  @javax.annotation.Nullable
  public String getSystem$getServiceLogs() {
    return system$getServiceLogs;
  }

  public void setSystem$getServiceLogs(@javax.annotation.Nullable String system$getServiceLogs) {
    this.system$getServiceLogs = system$getServiceLogs;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FetchServiceLogs200Response fetchServiceLogs200Response = (FetchServiceLogs200Response) o;
    return Objects.equals(this.system$getServiceLogs, fetchServiceLogs200Response.system$getServiceLogs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(system$getServiceLogs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FetchServiceLogs200Response {\n");
    sb.append("    system$getServiceLogs: ").append(toIndentedString(system$getServiceLogs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("system$get_service_logs"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to FetchServiceLogs200Response
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!FetchServiceLogs200Response.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in FetchServiceLogs200Response is not found in the empty JSON string", FetchServiceLogs200Response.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!FetchServiceLogs200Response.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `FetchServiceLogs200Response` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("system$get_service_logs") != null && !jsonObj.get("system$get_service_logs").isJsonNull()) && !jsonObj.get("system$get_service_logs").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `system$get_service_logs` to be a primitive type in the JSON string but got `%s`", jsonObj.get("system$get_service_logs").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FetchServiceLogs200Response.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FetchServiceLogs200Response' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FetchServiceLogs200Response> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FetchServiceLogs200Response.class));

       return (TypeAdapter<T>) new TypeAdapter<FetchServiceLogs200Response>() {
           @Override
           public void write(JsonWriter out, FetchServiceLogs200Response value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public FetchServiceLogs200Response read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of FetchServiceLogs200Response given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of FetchServiceLogs200Response
   * @throws IOException if the JSON string is invalid with respect to FetchServiceLogs200Response
   */
  public static FetchServiceLogs200Response fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FetchServiceLogs200Response.class);
  }

  /**
   * Convert an instance of FetchServiceLogs200Response to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

