/*
 * Snowflake SQL API
 * The Snowflake SQL API is a REST API that you can use to access and update data in a Snowflake database. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.Arrays;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import eu.openanalytics.containerproxy.backend.spcs.client.JSON;

/**
 * QueryStatus
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-06T17:47:56.670263400+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
public class QueryStatus {
  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  @javax.annotation.Nullable
  private String code;

  public static final String SERIALIZED_NAME_SQL_STATE = "sqlState";
  @SerializedName(SERIALIZED_NAME_SQL_STATE)
  @javax.annotation.Nullable
  private String sqlState;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  @javax.annotation.Nullable
  private String message;

  public static final String SERIALIZED_NAME_STATEMENT_HANDLE = "statementHandle";
  @SerializedName(SERIALIZED_NAME_STATEMENT_HANDLE)
  @javax.annotation.Nonnull
  private UUID statementHandle;

  public static final String SERIALIZED_NAME_CREATED_ON = "createdOn";
  @SerializedName(SERIALIZED_NAME_CREATED_ON)
  @javax.annotation.Nullable
  private Long createdOn;

  public static final String SERIALIZED_NAME_STATEMENT_STATUS_URL = "statementStatusUrl";
  @SerializedName(SERIALIZED_NAME_STATEMENT_STATUS_URL)
  @javax.annotation.Nullable
  private URI statementStatusUrl;

  public QueryStatus() {
  }

  public QueryStatus code(@javax.annotation.Nullable String code) {
    this.code = code;
    return this;
  }

  /**
   * Get code
   * @return code
   */
  @javax.annotation.Nullable
  public String getCode() {
    return code;
  }

  public void setCode(@javax.annotation.Nullable String code) {
    this.code = code;
  }


  public QueryStatus sqlState(@javax.annotation.Nullable String sqlState) {
    this.sqlState = sqlState;
    return this;
  }

  /**
   * Get sqlState
   * @return sqlState
   */
  @javax.annotation.Nullable
  public String getSqlState() {
    return sqlState;
  }

  public void setSqlState(@javax.annotation.Nullable String sqlState) {
    this.sqlState = sqlState;
  }


  public QueryStatus message(@javax.annotation.Nullable String message) {
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @javax.annotation.Nullable
  public String getMessage() {
    return message;
  }

  public void setMessage(@javax.annotation.Nullable String message) {
    this.message = message;
  }


  public QueryStatus statementHandle(@javax.annotation.Nonnull UUID statementHandle) {
    this.statementHandle = statementHandle;
    return this;
  }

  /**
   * Get statementHandle
   * @return statementHandle
   */
  @javax.annotation.Nonnull
  public UUID getStatementHandle() {
    return statementHandle;
  }

  public void setStatementHandle(@javax.annotation.Nonnull UUID statementHandle) {
    this.statementHandle = statementHandle;
  }


  public QueryStatus createdOn(@javax.annotation.Nullable Long createdOn) {
    this.createdOn = createdOn;
    return this;
  }

  /**
   * Timestamp that specifies when the statement execution started. The timestamp is expressed in milliseconds since the epoch.
   * @return createdOn
   */
  @javax.annotation.Nullable
  public Long getCreatedOn() {
    return createdOn;
  }

  public void setCreatedOn(@javax.annotation.Nullable Long createdOn) {
    this.createdOn = createdOn;
  }


  public QueryStatus statementStatusUrl(@javax.annotation.Nullable URI statementStatusUrl) {
    this.statementStatusUrl = statementStatusUrl;
    return this;
  }

  /**
   * URL that you can use to check the status of the execution of the statement and the result set.
   * @return statementStatusUrl
   */
  @javax.annotation.Nullable
  public URI getStatementStatusUrl() {
    return statementStatusUrl;
  }

  public void setStatementStatusUrl(@javax.annotation.Nullable URI statementStatusUrl) {
    this.statementStatusUrl = statementStatusUrl;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryStatus queryStatus = (QueryStatus) o;
    return Objects.equals(this.code, queryStatus.code) &&
        Objects.equals(this.sqlState, queryStatus.sqlState) &&
        Objects.equals(this.message, queryStatus.message) &&
        Objects.equals(this.statementHandle, queryStatus.statementHandle) &&
        Objects.equals(this.createdOn, queryStatus.createdOn) &&
        Objects.equals(this.statementStatusUrl, queryStatus.statementStatusUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, sqlState, message, statementHandle, createdOn, statementStatusUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryStatus {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    sqlState: ").append(toIndentedString(sqlState)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    statementHandle: ").append(toIndentedString(statementHandle)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    statementStatusUrl: ").append(toIndentedString(statementStatusUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("code", "sqlState", "message", "statementHandle", "createdOn", "statementStatusUrl"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("statementHandle"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to QueryStatus
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!QueryStatus.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in QueryStatus is not found in the empty JSON string", QueryStatus.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!QueryStatus.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `QueryStatus` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : QueryStatus.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("code") != null && !jsonObj.get("code").isJsonNull()) && !jsonObj.get("code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("code").toString()));
      }
      if ((jsonObj.get("sqlState") != null && !jsonObj.get("sqlState").isJsonNull()) && !jsonObj.get("sqlState").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `sqlState` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sqlState").toString()));
      }
      if ((jsonObj.get("message") != null && !jsonObj.get("message").isJsonNull()) && !jsonObj.get("message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message").toString()));
      }
      if (!jsonObj.get("statementHandle").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `statementHandle` to be a primitive type in the JSON string but got `%s`", jsonObj.get("statementHandle").toString()));
      }
      if ((jsonObj.get("statementStatusUrl") != null && !jsonObj.get("statementStatusUrl").isJsonNull()) && !jsonObj.get("statementStatusUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `statementStatusUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("statementStatusUrl").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!QueryStatus.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'QueryStatus' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<QueryStatus> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(QueryStatus.class));

       return (TypeAdapter<T>) new TypeAdapter<QueryStatus>() {
           @Override
           public void write(JsonWriter out, QueryStatus value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public QueryStatus read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of QueryStatus given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of QueryStatus
   * @throws IOException if the JSON string is invalid with respect to QueryStatus
   */
  public static QueryStatus fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, QueryStatus.class);
  }

  /**
   * Convert an instance of QueryStatus to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

