/*
 * Snowflake SQL API
 * The Snowflake SQL API is a REST API that you can use to access and update data in a Snowflake database. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import eu.openanalytics.containerproxy.backend.spcs.client.JSON;

/**
 * ResultSetResultSetMetaDataRowTypeInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-06T17:47:56.670263400+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
public class ResultSetResultSetMetaDataRowTypeInner {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nullable
  private String type;

  public static final String SERIALIZED_NAME_LENGTH = "length";
  @SerializedName(SERIALIZED_NAME_LENGTH)
  @javax.annotation.Nullable
  private Long length;

  public static final String SERIALIZED_NAME_PRECISION = "precision";
  @SerializedName(SERIALIZED_NAME_PRECISION)
  @javax.annotation.Nullable
  private Long precision;

  public static final String SERIALIZED_NAME_SCALE = "scale";
  @SerializedName(SERIALIZED_NAME_SCALE)
  @javax.annotation.Nullable
  private Long scale;

  public static final String SERIALIZED_NAME_NULLABLE = "nullable";
  @SerializedName(SERIALIZED_NAME_NULLABLE)
  @javax.annotation.Nullable
  private Boolean nullable;

  public ResultSetResultSetMetaDataRowTypeInner() {
  }

  public ResultSetResultSetMetaDataRowTypeInner name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public ResultSetResultSetMetaDataRowTypeInner type(@javax.annotation.Nullable String type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nullable
  public String getType() {
    return type;
  }

  public void setType(@javax.annotation.Nullable String type) {
    this.type = type;
  }


  public ResultSetResultSetMetaDataRowTypeInner length(@javax.annotation.Nullable Long length) {
    this.length = length;
    return this;
  }

  /**
   * Get length
   * minimum: 0
   * @return length
   */
  @javax.annotation.Nullable
  public Long getLength() {
    return length;
  }

  public void setLength(@javax.annotation.Nullable Long length) {
    this.length = length;
  }


  public ResultSetResultSetMetaDataRowTypeInner precision(@javax.annotation.Nullable Long precision) {
    this.precision = precision;
    return this;
  }

  /**
   * Get precision
   * minimum: 0
   * @return precision
   */
  @javax.annotation.Nullable
  public Long getPrecision() {
    return precision;
  }

  public void setPrecision(@javax.annotation.Nullable Long precision) {
    this.precision = precision;
  }


  public ResultSetResultSetMetaDataRowTypeInner scale(@javax.annotation.Nullable Long scale) {
    this.scale = scale;
    return this;
  }

  /**
   * Get scale
   * minimum: 0
   * @return scale
   */
  @javax.annotation.Nullable
  public Long getScale() {
    return scale;
  }

  public void setScale(@javax.annotation.Nullable Long scale) {
    this.scale = scale;
  }


  public ResultSetResultSetMetaDataRowTypeInner nullable(@javax.annotation.Nullable Boolean nullable) {
    this.nullable = nullable;
    return this;
  }

  /**
   * Get nullable
   * @return nullable
   */
  @javax.annotation.Nullable
  public Boolean getNullable() {
    return nullable;
  }

  public void setNullable(@javax.annotation.Nullable Boolean nullable) {
    this.nullable = nullable;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResultSetResultSetMetaDataRowTypeInner resultSetResultSetMetaDataRowTypeInner = (ResultSetResultSetMetaDataRowTypeInner) o;
    return Objects.equals(this.name, resultSetResultSetMetaDataRowTypeInner.name) &&
        Objects.equals(this.type, resultSetResultSetMetaDataRowTypeInner.type) &&
        Objects.equals(this.length, resultSetResultSetMetaDataRowTypeInner.length) &&
        Objects.equals(this.precision, resultSetResultSetMetaDataRowTypeInner.precision) &&
        Objects.equals(this.scale, resultSetResultSetMetaDataRowTypeInner.scale) &&
        Objects.equals(this.nullable, resultSetResultSetMetaDataRowTypeInner.nullable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, type, length, precision, scale, nullable);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResultSetResultSetMetaDataRowTypeInner {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    precision: ").append(toIndentedString(precision)).append("\n");
    sb.append("    scale: ").append(toIndentedString(scale)).append("\n");
    sb.append("    nullable: ").append(toIndentedString(nullable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("name", "type", "length", "precision", "scale", "nullable"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ResultSetResultSetMetaDataRowTypeInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ResultSetResultSetMetaDataRowTypeInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in ResultSetResultSetMetaDataRowTypeInner is not found in the empty JSON string", ResultSetResultSetMetaDataRowTypeInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ResultSetResultSetMetaDataRowTypeInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ResultSetResultSetMetaDataRowTypeInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ResultSetResultSetMetaDataRowTypeInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ResultSetResultSetMetaDataRowTypeInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ResultSetResultSetMetaDataRowTypeInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ResultSetResultSetMetaDataRowTypeInner.class));

       return (TypeAdapter<T>) new TypeAdapter<ResultSetResultSetMetaDataRowTypeInner>() {
           @Override
           public void write(JsonWriter out, ResultSetResultSetMetaDataRowTypeInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ResultSetResultSetMetaDataRowTypeInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ResultSetResultSetMetaDataRowTypeInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ResultSetResultSetMetaDataRowTypeInner
   * @throws IOException if the JSON string is invalid with respect to ResultSetResultSetMetaDataRowTypeInner
   */
  public static ResultSetResultSetMetaDataRowTypeInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ResultSetResultSetMetaDataRowTypeInner.class);
  }

  /**
   * Convert an instance of ResultSetResultSetMetaDataRowTypeInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

