/*
 * Snowflake SQL API
 * The Snowflake SQL API is a REST API that you can use to access and update data in a Snowflake database. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Locale;
import eu.openanalytics.containerproxy.backend.spcs.client.model.ResultSetResultSetMetaData;
import eu.openanalytics.containerproxy.backend.spcs.client.model.ResultSetStats;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import eu.openanalytics.containerproxy.backend.spcs.client.JSON;

/**
 * ResultSet
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-06T17:47:56.670263400+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
public class ResultSet {
  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  @javax.annotation.Nullable
  private String code;

  public static final String SERIALIZED_NAME_SQL_STATE = "sqlState";
  @SerializedName(SERIALIZED_NAME_SQL_STATE)
  @javax.annotation.Nullable
  private String sqlState;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  @javax.annotation.Nullable
  private String message;

  public static final String SERIALIZED_NAME_STATEMENT_HANDLE = "statementHandle";
  @SerializedName(SERIALIZED_NAME_STATEMENT_HANDLE)
  @javax.annotation.Nullable
  private UUID statementHandle;

  public static final String SERIALIZED_NAME_CREATED_ON = "createdOn";
  @SerializedName(SERIALIZED_NAME_CREATED_ON)
  @javax.annotation.Nullable
  private Long createdOn;

  public static final String SERIALIZED_NAME_STATEMENT_STATUS_URL = "statementStatusUrl";
  @SerializedName(SERIALIZED_NAME_STATEMENT_STATUS_URL)
  @javax.annotation.Nullable
  private URI statementStatusUrl;

  public static final String SERIALIZED_NAME_RESULT_SET_META_DATA = "resultSetMetaData";
  @SerializedName(SERIALIZED_NAME_RESULT_SET_META_DATA)
  @javax.annotation.Nullable
  private ResultSetResultSetMetaData resultSetMetaData;

  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  @javax.annotation.Nullable
  private List<List<String>> data = new ArrayList<>();

  public static final String SERIALIZED_NAME_STATS = "stats";
  @SerializedName(SERIALIZED_NAME_STATS)
  @javax.annotation.Nullable
  private ResultSetStats stats;

  public ResultSet() {
  }

  public ResultSet code(@javax.annotation.Nullable String code) {
    this.code = code;
    return this;
  }

  /**
   * Get code
   * @return code
   */
  @javax.annotation.Nullable
  public String getCode() {
    return code;
  }

  public void setCode(@javax.annotation.Nullable String code) {
    this.code = code;
  }


  public ResultSet sqlState(@javax.annotation.Nullable String sqlState) {
    this.sqlState = sqlState;
    return this;
  }

  /**
   * Get sqlState
   * @return sqlState
   */
  @javax.annotation.Nullable
  public String getSqlState() {
    return sqlState;
  }

  public void setSqlState(@javax.annotation.Nullable String sqlState) {
    this.sqlState = sqlState;
  }


  public ResultSet message(@javax.annotation.Nullable String message) {
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @javax.annotation.Nullable
  public String getMessage() {
    return message;
  }

  public void setMessage(@javax.annotation.Nullable String message) {
    this.message = message;
  }


  public ResultSet statementHandle(@javax.annotation.Nullable UUID statementHandle) {
    this.statementHandle = statementHandle;
    return this;
  }

  /**
   * Get statementHandle
   * @return statementHandle
   */
  @javax.annotation.Nullable
  public UUID getStatementHandle() {
    return statementHandle;
  }

  public void setStatementHandle(@javax.annotation.Nullable UUID statementHandle) {
    this.statementHandle = statementHandle;
  }


  public ResultSet createdOn(@javax.annotation.Nullable Long createdOn) {
    this.createdOn = createdOn;
    return this;
  }

  /**
   * Timestamp that specifies when the statement execution started.‌ The timestamp is expressed in milliseconds since the epoch.‌
   * @return createdOn
   */
  @javax.annotation.Nullable
  public Long getCreatedOn() {
    return createdOn;
  }

  public void setCreatedOn(@javax.annotation.Nullable Long createdOn) {
    this.createdOn = createdOn;
  }


  public ResultSet statementStatusUrl(@javax.annotation.Nullable URI statementStatusUrl) {
    this.statementStatusUrl = statementStatusUrl;
    return this;
  }

  /**
   * Get statementStatusUrl
   * @return statementStatusUrl
   */
  @javax.annotation.Nullable
  public URI getStatementStatusUrl() {
    return statementStatusUrl;
  }

  public void setStatementStatusUrl(@javax.annotation.Nullable URI statementStatusUrl) {
    this.statementStatusUrl = statementStatusUrl;
  }


  public ResultSet resultSetMetaData(@javax.annotation.Nullable ResultSetResultSetMetaData resultSetMetaData) {
    this.resultSetMetaData = resultSetMetaData;
    return this;
  }

  /**
   * Get resultSetMetaData
   * @return resultSetMetaData
   */
  @javax.annotation.Nullable
  public ResultSetResultSetMetaData getResultSetMetaData() {
    return resultSetMetaData;
  }

  public void setResultSetMetaData(@javax.annotation.Nullable ResultSetResultSetMetaData resultSetMetaData) {
    this.resultSetMetaData = resultSetMetaData;
  }


  public ResultSet data(@javax.annotation.Nullable List<List<String>> data) {
    this.data = data;
    return this;
  }

  public ResultSet addDataItem(List<String> dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

  /**
   * Result set data.
   * @return data
   */
  @javax.annotation.Nullable
  public List<List<String>> getData() {
    return data;
  }

  public void setData(@javax.annotation.Nullable List<List<String>> data) {
    this.data = data;
  }


  public ResultSet stats(@javax.annotation.Nullable ResultSetStats stats) {
    this.stats = stats;
    return this;
  }

  /**
   * Get stats
   * @return stats
   */
  @javax.annotation.Nullable
  public ResultSetStats getStats() {
    return stats;
  }

  public void setStats(@javax.annotation.Nullable ResultSetStats stats) {
    this.stats = stats;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResultSet resultSet = (ResultSet) o;
    return Objects.equals(this.code, resultSet.code) &&
        Objects.equals(this.sqlState, resultSet.sqlState) &&
        Objects.equals(this.message, resultSet.message) &&
        Objects.equals(this.statementHandle, resultSet.statementHandle) &&
        Objects.equals(this.createdOn, resultSet.createdOn) &&
        Objects.equals(this.statementStatusUrl, resultSet.statementStatusUrl) &&
        Objects.equals(this.resultSetMetaData, resultSet.resultSetMetaData) &&
        Objects.equals(this.data, resultSet.data) &&
        Objects.equals(this.stats, resultSet.stats);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, sqlState, message, statementHandle, createdOn, statementStatusUrl, resultSetMetaData, data, stats);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResultSet {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    sqlState: ").append(toIndentedString(sqlState)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    statementHandle: ").append(toIndentedString(statementHandle)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    statementStatusUrl: ").append(toIndentedString(statementStatusUrl)).append("\n");
    sb.append("    resultSetMetaData: ").append(toIndentedString(resultSetMetaData)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    stats: ").append(toIndentedString(stats)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("code", "sqlState", "message", "statementHandle", "createdOn", "statementStatusUrl", "resultSetMetaData", "data", "stats"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ResultSet
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ResultSet.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in ResultSet is not found in the empty JSON string", ResultSet.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ResultSet.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ResultSet` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("code") != null && !jsonObj.get("code").isJsonNull()) && !jsonObj.get("code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("code").toString()));
      }
      if ((jsonObj.get("sqlState") != null && !jsonObj.get("sqlState").isJsonNull()) && !jsonObj.get("sqlState").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `sqlState` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sqlState").toString()));
      }
      if ((jsonObj.get("message") != null && !jsonObj.get("message").isJsonNull()) && !jsonObj.get("message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message").toString()));
      }
      if ((jsonObj.get("statementHandle") != null && !jsonObj.get("statementHandle").isJsonNull()) && !jsonObj.get("statementHandle").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `statementHandle` to be a primitive type in the JSON string but got `%s`", jsonObj.get("statementHandle").toString()));
      }
      if ((jsonObj.get("statementStatusUrl") != null && !jsonObj.get("statementStatusUrl").isJsonNull()) && !jsonObj.get("statementStatusUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `statementStatusUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("statementStatusUrl").toString()));
      }
      // validate the optional field `resultSetMetaData`
      if (jsonObj.get("resultSetMetaData") != null && !jsonObj.get("resultSetMetaData").isJsonNull()) {
        ResultSetResultSetMetaData.validateJsonElement(jsonObj.get("resultSetMetaData"));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("data") != null && !jsonObj.get("data").isJsonNull() && !jsonObj.get("data").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `data` to be an array in the JSON string but got `%s`", jsonObj.get("data").toString()));
      }
      // validate the optional field `stats`
      if (jsonObj.get("stats") != null && !jsonObj.get("stats").isJsonNull()) {
        ResultSetStats.validateJsonElement(jsonObj.get("stats"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ResultSet.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ResultSet' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ResultSet> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ResultSet.class));

       return (TypeAdapter<T>) new TypeAdapter<ResultSet>() {
           @Override
           public void write(JsonWriter out, ResultSet value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ResultSet read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ResultSet given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ResultSet
   * @throws IOException if the JSON string is invalid with respect to ResultSet
   */
  public static ResultSet fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ResultSet.class);
  }

  /**
   * Convert an instance of ResultSet to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

