/*
 * Snowflake SQL API
 * The Snowflake SQL API is a REST API that you can use to access and update data in a Snowflake database. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import eu.openanalytics.containerproxy.backend.spcs.client.JSON;

/**
 * ResultSetResultSetMetaDataParameters
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-06T17:47:56.670263400+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
public class ResultSetResultSetMetaDataParameters {
  public static final String SERIALIZED_NAME_BINARY_OUTPUT_FORMAT = "binary_output_format";
  @SerializedName(SERIALIZED_NAME_BINARY_OUTPUT_FORMAT)
  @javax.annotation.Nullable
  private String binaryOutputFormat;

  public static final String SERIALIZED_NAME_DATE_OUTPUT_FORMAT = "date_output_format";
  @SerializedName(SERIALIZED_NAME_DATE_OUTPUT_FORMAT)
  @javax.annotation.Nullable
  private String dateOutputFormat;

  public static final String SERIALIZED_NAME_TIME_OUTPUT_FORMAT = "time_output_format";
  @SerializedName(SERIALIZED_NAME_TIME_OUTPUT_FORMAT)
  @javax.annotation.Nullable
  private String timeOutputFormat;

  public static final String SERIALIZED_NAME_TIMESTAMP_OUTPUT_FORMAT = "timestamp_output_format";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP_OUTPUT_FORMAT)
  @javax.annotation.Nullable
  private String timestampOutputFormat;

  public static final String SERIALIZED_NAME_TIMESTAMP_LTZ_OUTPUT_FORMAT = "timestamp_ltz_output_format";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP_LTZ_OUTPUT_FORMAT)
  @javax.annotation.Nullable
  private String timestampLtzOutputFormat;

  public static final String SERIALIZED_NAME_TIMESTAMP_NTZ_OUTPUT_FORMAT = "timestamp_ntz_output_format";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP_NTZ_OUTPUT_FORMAT)
  @javax.annotation.Nullable
  private String timestampNtzOutputFormat;

  public static final String SERIALIZED_NAME_TIMESTAMP_TZ_OUTPUT_FORMAT = "timestamp_tz_output_format";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP_TZ_OUTPUT_FORMAT)
  @javax.annotation.Nullable
  private String timestampTzOutputFormat;

  public static final String SERIALIZED_NAME_MULTI_STATEMENT_COUNT = "multi_statement_count";
  @SerializedName(SERIALIZED_NAME_MULTI_STATEMENT_COUNT)
  @javax.annotation.Nullable
  private Integer multiStatementCount;

  public ResultSetResultSetMetaDataParameters() {
  }

  public ResultSetResultSetMetaDataParameters binaryOutputFormat(@javax.annotation.Nullable String binaryOutputFormat) {
    this.binaryOutputFormat = binaryOutputFormat;
    return this;
  }

  /**
   * Get binaryOutputFormat
   * @return binaryOutputFormat
   */
  @javax.annotation.Nullable
  public String getBinaryOutputFormat() {
    return binaryOutputFormat;
  }

  public void setBinaryOutputFormat(@javax.annotation.Nullable String binaryOutputFormat) {
    this.binaryOutputFormat = binaryOutputFormat;
  }


  public ResultSetResultSetMetaDataParameters dateOutputFormat(@javax.annotation.Nullable String dateOutputFormat) {
    this.dateOutputFormat = dateOutputFormat;
    return this;
  }

  /**
   * Get dateOutputFormat
   * @return dateOutputFormat
   */
  @javax.annotation.Nullable
  public String getDateOutputFormat() {
    return dateOutputFormat;
  }

  public void setDateOutputFormat(@javax.annotation.Nullable String dateOutputFormat) {
    this.dateOutputFormat = dateOutputFormat;
  }


  public ResultSetResultSetMetaDataParameters timeOutputFormat(@javax.annotation.Nullable String timeOutputFormat) {
    this.timeOutputFormat = timeOutputFormat;
    return this;
  }

  /**
   * Get timeOutputFormat
   * @return timeOutputFormat
   */
  @javax.annotation.Nullable
  public String getTimeOutputFormat() {
    return timeOutputFormat;
  }

  public void setTimeOutputFormat(@javax.annotation.Nullable String timeOutputFormat) {
    this.timeOutputFormat = timeOutputFormat;
  }


  public ResultSetResultSetMetaDataParameters timestampOutputFormat(@javax.annotation.Nullable String timestampOutputFormat) {
    this.timestampOutputFormat = timestampOutputFormat;
    return this;
  }

  /**
   * Get timestampOutputFormat
   * @return timestampOutputFormat
   */
  @javax.annotation.Nullable
  public String getTimestampOutputFormat() {
    return timestampOutputFormat;
  }

  public void setTimestampOutputFormat(@javax.annotation.Nullable String timestampOutputFormat) {
    this.timestampOutputFormat = timestampOutputFormat;
  }


  public ResultSetResultSetMetaDataParameters timestampLtzOutputFormat(@javax.annotation.Nullable String timestampLtzOutputFormat) {
    this.timestampLtzOutputFormat = timestampLtzOutputFormat;
    return this;
  }

  /**
   * Get timestampLtzOutputFormat
   * @return timestampLtzOutputFormat
   */
  @javax.annotation.Nullable
  public String getTimestampLtzOutputFormat() {
    return timestampLtzOutputFormat;
  }

  public void setTimestampLtzOutputFormat(@javax.annotation.Nullable String timestampLtzOutputFormat) {
    this.timestampLtzOutputFormat = timestampLtzOutputFormat;
  }


  public ResultSetResultSetMetaDataParameters timestampNtzOutputFormat(@javax.annotation.Nullable String timestampNtzOutputFormat) {
    this.timestampNtzOutputFormat = timestampNtzOutputFormat;
    return this;
  }

  /**
   * Get timestampNtzOutputFormat
   * @return timestampNtzOutputFormat
   */
  @javax.annotation.Nullable
  public String getTimestampNtzOutputFormat() {
    return timestampNtzOutputFormat;
  }

  public void setTimestampNtzOutputFormat(@javax.annotation.Nullable String timestampNtzOutputFormat) {
    this.timestampNtzOutputFormat = timestampNtzOutputFormat;
  }


  public ResultSetResultSetMetaDataParameters timestampTzOutputFormat(@javax.annotation.Nullable String timestampTzOutputFormat) {
    this.timestampTzOutputFormat = timestampTzOutputFormat;
    return this;
  }

  /**
   * Get timestampTzOutputFormat
   * @return timestampTzOutputFormat
   */
  @javax.annotation.Nullable
  public String getTimestampTzOutputFormat() {
    return timestampTzOutputFormat;
  }

  public void setTimestampTzOutputFormat(@javax.annotation.Nullable String timestampTzOutputFormat) {
    this.timestampTzOutputFormat = timestampTzOutputFormat;
  }


  public ResultSetResultSetMetaDataParameters multiStatementCount(@javax.annotation.Nullable Integer multiStatementCount) {
    this.multiStatementCount = multiStatementCount;
    return this;
  }

  /**
   * Get multiStatementCount
   * @return multiStatementCount
   */
  @javax.annotation.Nullable
  public Integer getMultiStatementCount() {
    return multiStatementCount;
  }

  public void setMultiStatementCount(@javax.annotation.Nullable Integer multiStatementCount) {
    this.multiStatementCount = multiStatementCount;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResultSetResultSetMetaDataParameters resultSetResultSetMetaDataParameters = (ResultSetResultSetMetaDataParameters) o;
    return Objects.equals(this.binaryOutputFormat, resultSetResultSetMetaDataParameters.binaryOutputFormat) &&
        Objects.equals(this.dateOutputFormat, resultSetResultSetMetaDataParameters.dateOutputFormat) &&
        Objects.equals(this.timeOutputFormat, resultSetResultSetMetaDataParameters.timeOutputFormat) &&
        Objects.equals(this.timestampOutputFormat, resultSetResultSetMetaDataParameters.timestampOutputFormat) &&
        Objects.equals(this.timestampLtzOutputFormat, resultSetResultSetMetaDataParameters.timestampLtzOutputFormat) &&
        Objects.equals(this.timestampNtzOutputFormat, resultSetResultSetMetaDataParameters.timestampNtzOutputFormat) &&
        Objects.equals(this.timestampTzOutputFormat, resultSetResultSetMetaDataParameters.timestampTzOutputFormat) &&
        Objects.equals(this.multiStatementCount, resultSetResultSetMetaDataParameters.multiStatementCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(binaryOutputFormat, dateOutputFormat, timeOutputFormat, timestampOutputFormat, timestampLtzOutputFormat, timestampNtzOutputFormat, timestampTzOutputFormat, multiStatementCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResultSetResultSetMetaDataParameters {\n");
    sb.append("    binaryOutputFormat: ").append(toIndentedString(binaryOutputFormat)).append("\n");
    sb.append("    dateOutputFormat: ").append(toIndentedString(dateOutputFormat)).append("\n");
    sb.append("    timeOutputFormat: ").append(toIndentedString(timeOutputFormat)).append("\n");
    sb.append("    timestampOutputFormat: ").append(toIndentedString(timestampOutputFormat)).append("\n");
    sb.append("    timestampLtzOutputFormat: ").append(toIndentedString(timestampLtzOutputFormat)).append("\n");
    sb.append("    timestampNtzOutputFormat: ").append(toIndentedString(timestampNtzOutputFormat)).append("\n");
    sb.append("    timestampTzOutputFormat: ").append(toIndentedString(timestampTzOutputFormat)).append("\n");
    sb.append("    multiStatementCount: ").append(toIndentedString(multiStatementCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("binary_output_format", "date_output_format", "time_output_format", "timestamp_output_format", "timestamp_ltz_output_format", "timestamp_ntz_output_format", "timestamp_tz_output_format", "multi_statement_count"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ResultSetResultSetMetaDataParameters
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ResultSetResultSetMetaDataParameters.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in ResultSetResultSetMetaDataParameters is not found in the empty JSON string", ResultSetResultSetMetaDataParameters.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ResultSetResultSetMetaDataParameters.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ResultSetResultSetMetaDataParameters` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("binary_output_format") != null && !jsonObj.get("binary_output_format").isJsonNull()) && !jsonObj.get("binary_output_format").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `binary_output_format` to be a primitive type in the JSON string but got `%s`", jsonObj.get("binary_output_format").toString()));
      }
      if ((jsonObj.get("date_output_format") != null && !jsonObj.get("date_output_format").isJsonNull()) && !jsonObj.get("date_output_format").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `date_output_format` to be a primitive type in the JSON string but got `%s`", jsonObj.get("date_output_format").toString()));
      }
      if ((jsonObj.get("time_output_format") != null && !jsonObj.get("time_output_format").isJsonNull()) && !jsonObj.get("time_output_format").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `time_output_format` to be a primitive type in the JSON string but got `%s`", jsonObj.get("time_output_format").toString()));
      }
      if ((jsonObj.get("timestamp_output_format") != null && !jsonObj.get("timestamp_output_format").isJsonNull()) && !jsonObj.get("timestamp_output_format").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `timestamp_output_format` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timestamp_output_format").toString()));
      }
      if ((jsonObj.get("timestamp_ltz_output_format") != null && !jsonObj.get("timestamp_ltz_output_format").isJsonNull()) && !jsonObj.get("timestamp_ltz_output_format").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `timestamp_ltz_output_format` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timestamp_ltz_output_format").toString()));
      }
      if ((jsonObj.get("timestamp_ntz_output_format") != null && !jsonObj.get("timestamp_ntz_output_format").isJsonNull()) && !jsonObj.get("timestamp_ntz_output_format").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `timestamp_ntz_output_format` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timestamp_ntz_output_format").toString()));
      }
      if ((jsonObj.get("timestamp_tz_output_format") != null && !jsonObj.get("timestamp_tz_output_format").isJsonNull()) && !jsonObj.get("timestamp_tz_output_format").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `timestamp_tz_output_format` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timestamp_tz_output_format").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ResultSetResultSetMetaDataParameters.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ResultSetResultSetMetaDataParameters' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ResultSetResultSetMetaDataParameters> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ResultSetResultSetMetaDataParameters.class));

       return (TypeAdapter<T>) new TypeAdapter<ResultSetResultSetMetaDataParameters>() {
           @Override
           public void write(JsonWriter out, ResultSetResultSetMetaDataParameters value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ResultSetResultSetMetaDataParameters read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ResultSetResultSetMetaDataParameters given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ResultSetResultSetMetaDataParameters
   * @throws IOException if the JSON string is invalid with respect to ResultSetResultSetMetaDataParameters
   */
  public static ResultSetResultSetMetaDataParameters fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ResultSetResultSetMetaDataParameters.class);
  }

  /**
   * Convert an instance of ResultSetResultSetMetaDataParameters to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

