/*
 * Snowflake SQL API
 * The Snowflake SQL API is a REST API that you can use to access and update data in a Snowflake database. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Locale;
import eu.openanalytics.containerproxy.backend.spcs.client.model.ResultSetResultSetMetaDataParameters;
import eu.openanalytics.containerproxy.backend.spcs.client.model.ResultSetResultSetMetaDataPartitionInfoInner;
import eu.openanalytics.containerproxy.backend.spcs.client.model.ResultSetResultSetMetaDataRowTypeInner;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import eu.openanalytics.containerproxy.backend.spcs.client.JSON;

/**
 * ResultSetResultSetMetaData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-06T17:47:56.670263400+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
public class ResultSetResultSetMetaData {
  /**
   * For v2 endpoints the only possible value for this field is jsonv2.
   */
  @JsonAdapter(FormatEnum.Adapter.class)
  public enum FormatEnum {
    JSONV2("jsonv2");

    private String value;

    FormatEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static FormatEnum fromValue(String value) {
      for (FormatEnum b : FormatEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<FormatEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FormatEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public FormatEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return FormatEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      FormatEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_FORMAT = "format";
  @SerializedName(SERIALIZED_NAME_FORMAT)
  @javax.annotation.Nullable
  private FormatEnum format;

  public static final String SERIALIZED_NAME_NUM_ROWS = "numRows";
  @SerializedName(SERIALIZED_NAME_NUM_ROWS)
  @javax.annotation.Nullable
  private Long numRows;

  public static final String SERIALIZED_NAME_ROW_TYPE = "rowType";
  @SerializedName(SERIALIZED_NAME_ROW_TYPE)
  @javax.annotation.Nullable
  private List<ResultSetResultSetMetaDataRowTypeInner> rowType = new ArrayList<>();

  public static final String SERIALIZED_NAME_PARTITION_INFO = "partitionInfo";
  @SerializedName(SERIALIZED_NAME_PARTITION_INFO)
  @javax.annotation.Nullable
  private List<ResultSetResultSetMetaDataPartitionInfoInner> partitionInfo = new ArrayList<>();

  public static final String SERIALIZED_NAME_NULLABLE = "nullable";
  @SerializedName(SERIALIZED_NAME_NULLABLE)
  @javax.annotation.Nullable
  private Boolean nullable;

  public static final String SERIALIZED_NAME_PARAMETERS = "parameters";
  @SerializedName(SERIALIZED_NAME_PARAMETERS)
  @javax.annotation.Nullable
  private ResultSetResultSetMetaDataParameters parameters;

  public ResultSetResultSetMetaData() {
  }

  public ResultSetResultSetMetaData format(@javax.annotation.Nullable FormatEnum format) {
    this.format = format;
    return this;
  }

  /**
   * For v2 endpoints the only possible value for this field is jsonv2.
   * @return format
   */
  @javax.annotation.Nullable
  public FormatEnum getFormat() {
    return format;
  }

  public void setFormat(@javax.annotation.Nullable FormatEnum format) {
    this.format = format;
  }


  public ResultSetResultSetMetaData numRows(@javax.annotation.Nullable Long numRows) {
    this.numRows = numRows;
    return this;
  }

  /**
   * The total number of rows of results.
   * @return numRows
   */
  @javax.annotation.Nullable
  public Long getNumRows() {
    return numRows;
  }

  public void setNumRows(@javax.annotation.Nullable Long numRows) {
    this.numRows = numRows;
  }


  public ResultSetResultSetMetaData rowType(@javax.annotation.Nullable List<ResultSetResultSetMetaDataRowTypeInner> rowType) {
    this.rowType = rowType;
    return this;
  }

  public ResultSetResultSetMetaData addRowTypeItem(ResultSetResultSetMetaDataRowTypeInner rowTypeItem) {
    if (this.rowType == null) {
      this.rowType = new ArrayList<>();
    }
    this.rowType.add(rowTypeItem);
    return this;
  }

  /**
   * Get rowType
   * @return rowType
   */
  @javax.annotation.Nullable
  public List<ResultSetResultSetMetaDataRowTypeInner> getRowType() {
    return rowType;
  }

  public void setRowType(@javax.annotation.Nullable List<ResultSetResultSetMetaDataRowTypeInner> rowType) {
    this.rowType = rowType;
  }


  public ResultSetResultSetMetaData partitionInfo(@javax.annotation.Nullable List<ResultSetResultSetMetaDataPartitionInfoInner> partitionInfo) {
    this.partitionInfo = partitionInfo;
    return this;
  }

  public ResultSetResultSetMetaData addPartitionInfoItem(ResultSetResultSetMetaDataPartitionInfoInner partitionInfoItem) {
    if (this.partitionInfo == null) {
      this.partitionInfo = new ArrayList<>();
    }
    this.partitionInfo.add(partitionInfoItem);
    return this;
  }

  /**
   * Partition information
   * @return partitionInfo
   */
  @javax.annotation.Nullable
  public List<ResultSetResultSetMetaDataPartitionInfoInner> getPartitionInfo() {
    return partitionInfo;
  }

  public void setPartitionInfo(@javax.annotation.Nullable List<ResultSetResultSetMetaDataPartitionInfoInner> partitionInfo) {
    this.partitionInfo = partitionInfo;
  }


  public ResultSetResultSetMetaData nullable(@javax.annotation.Nullable Boolean nullable) {
    this.nullable = nullable;
    return this;
  }

  /**
   * false if null is replaced with a string &#39;null&#39; otherwise false
   * @return nullable
   */
  @javax.annotation.Nullable
  public Boolean getNullable() {
    return nullable;
  }

  public void setNullable(@javax.annotation.Nullable Boolean nullable) {
    this.nullable = nullable;
  }


  public ResultSetResultSetMetaData parameters(@javax.annotation.Nullable ResultSetResultSetMetaDataParameters parameters) {
    this.parameters = parameters;
    return this;
  }

  /**
   * Get parameters
   * @return parameters
   */
  @javax.annotation.Nullable
  public ResultSetResultSetMetaDataParameters getParameters() {
    return parameters;
  }

  public void setParameters(@javax.annotation.Nullable ResultSetResultSetMetaDataParameters parameters) {
    this.parameters = parameters;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResultSetResultSetMetaData resultSetResultSetMetaData = (ResultSetResultSetMetaData) o;
    return Objects.equals(this.format, resultSetResultSetMetaData.format) &&
        Objects.equals(this.numRows, resultSetResultSetMetaData.numRows) &&
        Objects.equals(this.rowType, resultSetResultSetMetaData.rowType) &&
        Objects.equals(this.partitionInfo, resultSetResultSetMetaData.partitionInfo) &&
        Objects.equals(this.nullable, resultSetResultSetMetaData.nullable) &&
        Objects.equals(this.parameters, resultSetResultSetMetaData.parameters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(format, numRows, rowType, partitionInfo, nullable, parameters);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResultSetResultSetMetaData {\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    numRows: ").append(toIndentedString(numRows)).append("\n");
    sb.append("    rowType: ").append(toIndentedString(rowType)).append("\n");
    sb.append("    partitionInfo: ").append(toIndentedString(partitionInfo)).append("\n");
    sb.append("    nullable: ").append(toIndentedString(nullable)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("format", "numRows", "rowType", "partitionInfo", "nullable", "parameters"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ResultSetResultSetMetaData
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ResultSetResultSetMetaData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in ResultSetResultSetMetaData is not found in the empty JSON string", ResultSetResultSetMetaData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ResultSetResultSetMetaData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ResultSetResultSetMetaData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("format") != null && !jsonObj.get("format").isJsonNull()) && !jsonObj.get("format").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `format` to be a primitive type in the JSON string but got `%s`", jsonObj.get("format").toString()));
      }
      // validate the optional field `format`
      if (jsonObj.get("format") != null && !jsonObj.get("format").isJsonNull()) {
        FormatEnum.validateJsonElement(jsonObj.get("format"));
      }
      if (jsonObj.get("rowType") != null && !jsonObj.get("rowType").isJsonNull()) {
        JsonArray jsonArrayrowType = jsonObj.getAsJsonArray("rowType");
        if (jsonArrayrowType != null) {
          // ensure the json data is an array
          if (!jsonObj.get("rowType").isJsonArray()) {
            throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `rowType` to be an array in the JSON string but got `%s`", jsonObj.get("rowType").toString()));
          }

          // validate the optional field `rowType` (array)
          for (int i = 0; i < jsonArrayrowType.size(); i++) {
            ResultSetResultSetMetaDataRowTypeInner.validateJsonElement(jsonArrayrowType.get(i));
          };
        }
      }
      if (jsonObj.get("partitionInfo") != null && !jsonObj.get("partitionInfo").isJsonNull()) {
        JsonArray jsonArraypartitionInfo = jsonObj.getAsJsonArray("partitionInfo");
        if (jsonArraypartitionInfo != null) {
          // ensure the json data is an array
          if (!jsonObj.get("partitionInfo").isJsonArray()) {
            throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `partitionInfo` to be an array in the JSON string but got `%s`", jsonObj.get("partitionInfo").toString()));
          }

          // validate the optional field `partitionInfo` (array)
          for (int i = 0; i < jsonArraypartitionInfo.size(); i++) {
            ResultSetResultSetMetaDataPartitionInfoInner.validateJsonElement(jsonArraypartitionInfo.get(i));
          };
        }
      }
      // validate the optional field `parameters`
      if (jsonObj.get("parameters") != null && !jsonObj.get("parameters").isJsonNull()) {
        ResultSetResultSetMetaDataParameters.validateJsonElement(jsonObj.get("parameters"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ResultSetResultSetMetaData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ResultSetResultSetMetaData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ResultSetResultSetMetaData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ResultSetResultSetMetaData.class));

       return (TypeAdapter<T>) new TypeAdapter<ResultSetResultSetMetaData>() {
           @Override
           public void write(JsonWriter out, ResultSetResultSetMetaData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ResultSetResultSetMetaData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ResultSetResultSetMetaData given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ResultSetResultSetMetaData
   * @throws IOException if the JSON string is invalid with respect to ResultSetResultSetMetaData
   */
  public static ResultSetResultSetMetaData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ResultSetResultSetMetaData.class);
  }

  /**
   * Convert an instance of ResultSetResultSetMetaData to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

