/*
 * Snowflake SQL API
 * The Snowflake SQL API is a REST API that you can use to access and update data in a Snowflake database. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import eu.openanalytics.containerproxy.backend.spcs.client.JSON;

/**
 * ResultSetResultSetMetaDataPartitionInfoInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-06T17:47:56.670263400+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
public class ResultSetResultSetMetaDataPartitionInfoInner {
  public static final String SERIALIZED_NAME_ROW_COUNT = "rowCount";
  @SerializedName(SERIALIZED_NAME_ROW_COUNT)
  @javax.annotation.Nullable
  private Long rowCount;

  public static final String SERIALIZED_NAME_COMPRESSED_SIZE = "compressedSize";
  @SerializedName(SERIALIZED_NAME_COMPRESSED_SIZE)
  @javax.annotation.Nullable
  private Long compressedSize;

  public static final String SERIALIZED_NAME_UNCOMPRESSED_SIZE = "uncompressedSize";
  @SerializedName(SERIALIZED_NAME_UNCOMPRESSED_SIZE)
  @javax.annotation.Nullable
  private Long uncompressedSize;

  public ResultSetResultSetMetaDataPartitionInfoInner() {
  }

  public ResultSetResultSetMetaDataPartitionInfoInner rowCount(@javax.annotation.Nullable Long rowCount) {
    this.rowCount = rowCount;
    return this;
  }

  /**
   * Number of rows in the partition.
   * minimum: 0
   * @return rowCount
   */
  @javax.annotation.Nullable
  public Long getRowCount() {
    return rowCount;
  }

  public void setRowCount(@javax.annotation.Nullable Long rowCount) {
    this.rowCount = rowCount;
  }


  public ResultSetResultSetMetaDataPartitionInfoInner compressedSize(@javax.annotation.Nullable Long compressedSize) {
    this.compressedSize = compressedSize;
    return this;
  }

  /**
   * the partition size before the decompression. This may or may not be present in the partitionInfo. Uncompressed size would always be there.
   * minimum: 0
   * @return compressedSize
   */
  @javax.annotation.Nullable
  public Long getCompressedSize() {
    return compressedSize;
  }

  public void setCompressedSize(@javax.annotation.Nullable Long compressedSize) {
    this.compressedSize = compressedSize;
  }


  public ResultSetResultSetMetaDataPartitionInfoInner uncompressedSize(@javax.annotation.Nullable Long uncompressedSize) {
    this.uncompressedSize = uncompressedSize;
    return this;
  }

  /**
   * the partition size after the decompression
   * minimum: 0
   * @return uncompressedSize
   */
  @javax.annotation.Nullable
  public Long getUncompressedSize() {
    return uncompressedSize;
  }

  public void setUncompressedSize(@javax.annotation.Nullable Long uncompressedSize) {
    this.uncompressedSize = uncompressedSize;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResultSetResultSetMetaDataPartitionInfoInner resultSetResultSetMetaDataPartitionInfoInner = (ResultSetResultSetMetaDataPartitionInfoInner) o;
    return Objects.equals(this.rowCount, resultSetResultSetMetaDataPartitionInfoInner.rowCount) &&
        Objects.equals(this.compressedSize, resultSetResultSetMetaDataPartitionInfoInner.compressedSize) &&
        Objects.equals(this.uncompressedSize, resultSetResultSetMetaDataPartitionInfoInner.uncompressedSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rowCount, compressedSize, uncompressedSize);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResultSetResultSetMetaDataPartitionInfoInner {\n");
    sb.append("    rowCount: ").append(toIndentedString(rowCount)).append("\n");
    sb.append("    compressedSize: ").append(toIndentedString(compressedSize)).append("\n");
    sb.append("    uncompressedSize: ").append(toIndentedString(uncompressedSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("rowCount", "compressedSize", "uncompressedSize"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ResultSetResultSetMetaDataPartitionInfoInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ResultSetResultSetMetaDataPartitionInfoInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in ResultSetResultSetMetaDataPartitionInfoInner is not found in the empty JSON string", ResultSetResultSetMetaDataPartitionInfoInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ResultSetResultSetMetaDataPartitionInfoInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ResultSetResultSetMetaDataPartitionInfoInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ResultSetResultSetMetaDataPartitionInfoInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ResultSetResultSetMetaDataPartitionInfoInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ResultSetResultSetMetaDataPartitionInfoInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ResultSetResultSetMetaDataPartitionInfoInner.class));

       return (TypeAdapter<T>) new TypeAdapter<ResultSetResultSetMetaDataPartitionInfoInner>() {
           @Override
           public void write(JsonWriter out, ResultSetResultSetMetaDataPartitionInfoInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ResultSetResultSetMetaDataPartitionInfoInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ResultSetResultSetMetaDataPartitionInfoInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ResultSetResultSetMetaDataPartitionInfoInner
   * @throws IOException if the JSON string is invalid with respect to ResultSetResultSetMetaDataPartitionInfoInner
   */
  public static ResultSetResultSetMetaDataPartitionInfoInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ResultSetResultSetMetaDataPartitionInfoInner.class);
  }

  /**
   * Convert an instance of ResultSetResultSetMetaDataPartitionInfoInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

