/*
 * Snowflake Services API
 * The Snowflake Services API is a REST API that you can use to access, update, and perform certain actions on Services resource in a Snowflake database.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import eu.openanalytics.containerproxy.backend.spcs.client.JSON;

/**
 * ServiceContainer
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-06T17:47:48.337179400+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
public class ServiceContainer {
  public static final String SERIALIZED_NAME_DATABASE_NAME = "database_name";
  @SerializedName(SERIALIZED_NAME_DATABASE_NAME)
  @javax.annotation.Nullable
  private String databaseName;

  public static final String SERIALIZED_NAME_SCHEMA_NAME = "schema_name";
  @SerializedName(SERIALIZED_NAME_SCHEMA_NAME)
  @javax.annotation.Nullable
  private String schemaName;

  public static final String SERIALIZED_NAME_SERVICE_NAME = "service_name";
  @SerializedName(SERIALIZED_NAME_SERVICE_NAME)
  @javax.annotation.Nullable
  private String serviceName;

  public static final String SERIALIZED_NAME_SERVICE_STATUS = "service_status";
  @SerializedName(SERIALIZED_NAME_SERVICE_STATUS)
  @javax.annotation.Nullable
  private String serviceStatus;

  public static final String SERIALIZED_NAME_INSTANCE_ID = "instance_id";
  @SerializedName(SERIALIZED_NAME_INSTANCE_ID)
  @javax.annotation.Nullable
  private String instanceId;

  public static final String SERIALIZED_NAME_INSTANCE_STATUS = "instance_status";
  @SerializedName(SERIALIZED_NAME_INSTANCE_STATUS)
  @javax.annotation.Nullable
  private String instanceStatus;

  public static final String SERIALIZED_NAME_CONTAINER_NAME = "container_name";
  @SerializedName(SERIALIZED_NAME_CONTAINER_NAME)
  @javax.annotation.Nullable
  private String containerName;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private String status;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  @javax.annotation.Nullable
  private String message;

  public static final String SERIALIZED_NAME_IMAGE_NAME = "image_name";
  @SerializedName(SERIALIZED_NAME_IMAGE_NAME)
  @javax.annotation.Nullable
  private String imageName;

  public static final String SERIALIZED_NAME_IMAGE_DIGEST = "image_digest";
  @SerializedName(SERIALIZED_NAME_IMAGE_DIGEST)
  @javax.annotation.Nullable
  private String imageDigest;

  public static final String SERIALIZED_NAME_RESTART_COUNT = "restart_count";
  @SerializedName(SERIALIZED_NAME_RESTART_COUNT)
  @javax.annotation.Nullable
  private Integer restartCount;

  public static final String SERIALIZED_NAME_START_TIME = "start_time";
  @SerializedName(SERIALIZED_NAME_START_TIME)
  @javax.annotation.Nullable
  private String startTime;

  public ServiceContainer() {
  }

  public ServiceContainer(
     String serviceStatus, 
     String instanceId, 
     String instanceStatus, 
     String containerName, 
     String status, 
     String message, 
     String imageName, 
     String imageDigest, 
     Integer restartCount, 
     String startTime
  ) {
    this();
    this.serviceStatus = serviceStatus;
    this.instanceId = instanceId;
    this.instanceStatus = instanceStatus;
    this.containerName = containerName;
    this.status = status;
    this.message = message;
    this.imageName = imageName;
    this.imageDigest = imageDigest;
    this.restartCount = restartCount;
    this.startTime = startTime;
  }

  public ServiceContainer databaseName(@javax.annotation.Nullable String databaseName) {
    this.databaseName = databaseName;
    return this;
  }

  /**
   * A Snowflake object identifier. If the identifier contains spaces or special characters, the entire string must be enclosed in double quotes. Identifiers enclosed in double quotes are also case-sensitive.
   * @return databaseName
   */
  @javax.annotation.Nullable
  public String getDatabaseName() {
    return databaseName;
  }

  public void setDatabaseName(@javax.annotation.Nullable String databaseName) {
    this.databaseName = databaseName;
  }


  public ServiceContainer schemaName(@javax.annotation.Nullable String schemaName) {
    this.schemaName = schemaName;
    return this;
  }

  /**
   * A Snowflake object identifier. If the identifier contains spaces or special characters, the entire string must be enclosed in double quotes. Identifiers enclosed in double quotes are also case-sensitive.
   * @return schemaName
   */
  @javax.annotation.Nullable
  public String getSchemaName() {
    return schemaName;
  }

  public void setSchemaName(@javax.annotation.Nullable String schemaName) {
    this.schemaName = schemaName;
  }


  public ServiceContainer serviceName(@javax.annotation.Nullable String serviceName) {
    this.serviceName = serviceName;
    return this;
  }

  /**
   * A Snowflake object identifier. If the identifier contains spaces or special characters, the entire string must be enclosed in double quotes. Identifiers enclosed in double quotes are also case-sensitive.
   * @return serviceName
   */
  @javax.annotation.Nullable
  public String getServiceName() {
    return serviceName;
  }

  public void setServiceName(@javax.annotation.Nullable String serviceName) {
    this.serviceName = serviceName;
  }


  /**
   * The current status of the service.
   * @return serviceStatus
   */
  @javax.annotation.Nullable
  public String getServiceStatus() {
    return serviceStatus;
  }



  /**
   * ID of the service instance (this is the index of the service instance starting from 0).
   * @return instanceId
   */
  @javax.annotation.Nullable
  public String getInstanceId() {
    return instanceId;
  }



  /**
   * The current status of the service instance.
   * @return instanceStatus
   */
  @javax.annotation.Nullable
  public String getInstanceStatus() {
    return instanceStatus;
  }



  /**
   * Name of the container.
   * @return containerName
   */
  @javax.annotation.Nullable
  public String getContainerName() {
    return containerName;
  }



  /**
   * Service container status.
   * @return status
   */
  @javax.annotation.Nullable
  public String getStatus() {
    return status;
  }



  /**
   * Additional clarification about status.
   * @return message
   */
  @javax.annotation.Nullable
  public String getMessage() {
    return message;
  }



  /**
   * Image name used to create the service container.
   * @return imageName
   */
  @javax.annotation.Nullable
  public String getImageName() {
    return imageName;
  }



  /**
   * The unique and immutable identifier representing the image content.
   * @return imageDigest
   */
  @javax.annotation.Nullable
  public String getImageDigest() {
    return imageDigest;
  }



  /**
   * Number of times Snowflake restarted the service.
   * @return restartCount
   */
  @javax.annotation.Nullable
  public Integer getRestartCount() {
    return restartCount;
  }



  /**
   * Date and time when the container started.
   * @return startTime
   */
  @javax.annotation.Nullable
  public String getStartTime() {
    return startTime;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceContainer serviceContainer = (ServiceContainer) o;
    return Objects.equals(this.databaseName, serviceContainer.databaseName) &&
        Objects.equals(this.schemaName, serviceContainer.schemaName) &&
        Objects.equals(this.serviceName, serviceContainer.serviceName) &&
        Objects.equals(this.serviceStatus, serviceContainer.serviceStatus) &&
        Objects.equals(this.instanceId, serviceContainer.instanceId) &&
        Objects.equals(this.instanceStatus, serviceContainer.instanceStatus) &&
        Objects.equals(this.containerName, serviceContainer.containerName) &&
        Objects.equals(this.status, serviceContainer.status) &&
        Objects.equals(this.message, serviceContainer.message) &&
        Objects.equals(this.imageName, serviceContainer.imageName) &&
        Objects.equals(this.imageDigest, serviceContainer.imageDigest) &&
        Objects.equals(this.restartCount, serviceContainer.restartCount) &&
        Objects.equals(this.startTime, serviceContainer.startTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(databaseName, schemaName, serviceName, serviceStatus, instanceId, instanceStatus, containerName, status, message, imageName, imageDigest, restartCount, startTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceContainer {\n");
    sb.append("    databaseName: ").append(toIndentedString(databaseName)).append("\n");
    sb.append("    schemaName: ").append(toIndentedString(schemaName)).append("\n");
    sb.append("    serviceName: ").append(toIndentedString(serviceName)).append("\n");
    sb.append("    serviceStatus: ").append(toIndentedString(serviceStatus)).append("\n");
    sb.append("    instanceId: ").append(toIndentedString(instanceId)).append("\n");
    sb.append("    instanceStatus: ").append(toIndentedString(instanceStatus)).append("\n");
    sb.append("    containerName: ").append(toIndentedString(containerName)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    imageName: ").append(toIndentedString(imageName)).append("\n");
    sb.append("    imageDigest: ").append(toIndentedString(imageDigest)).append("\n");
    sb.append("    restartCount: ").append(toIndentedString(restartCount)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("database_name", "schema_name", "service_name", "service_status", "instance_id", "instance_status", "container_name", "status", "message", "image_name", "image_digest", "restart_count", "start_time"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ServiceContainer
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ServiceContainer.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in ServiceContainer is not found in the empty JSON string", ServiceContainer.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ServiceContainer.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ServiceContainer` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("database_name") != null && !jsonObj.get("database_name").isJsonNull()) && !jsonObj.get("database_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `database_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("database_name").toString()));
      }
      if ((jsonObj.get("schema_name") != null && !jsonObj.get("schema_name").isJsonNull()) && !jsonObj.get("schema_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `schema_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("schema_name").toString()));
      }
      if ((jsonObj.get("service_name") != null && !jsonObj.get("service_name").isJsonNull()) && !jsonObj.get("service_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `service_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("service_name").toString()));
      }
      if ((jsonObj.get("service_status") != null && !jsonObj.get("service_status").isJsonNull()) && !jsonObj.get("service_status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `service_status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("service_status").toString()));
      }
      if ((jsonObj.get("instance_id") != null && !jsonObj.get("instance_id").isJsonNull()) && !jsonObj.get("instance_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `instance_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("instance_id").toString()));
      }
      if ((jsonObj.get("instance_status") != null && !jsonObj.get("instance_status").isJsonNull()) && !jsonObj.get("instance_status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `instance_status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("instance_status").toString()));
      }
      if ((jsonObj.get("container_name") != null && !jsonObj.get("container_name").isJsonNull()) && !jsonObj.get("container_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `container_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("container_name").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if ((jsonObj.get("message") != null && !jsonObj.get("message").isJsonNull()) && !jsonObj.get("message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message").toString()));
      }
      if ((jsonObj.get("image_name") != null && !jsonObj.get("image_name").isJsonNull()) && !jsonObj.get("image_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `image_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("image_name").toString()));
      }
      if ((jsonObj.get("image_digest") != null && !jsonObj.get("image_digest").isJsonNull()) && !jsonObj.get("image_digest").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `image_digest` to be a primitive type in the JSON string but got `%s`", jsonObj.get("image_digest").toString()));
      }
      if ((jsonObj.get("start_time") != null && !jsonObj.get("start_time").isJsonNull()) && !jsonObj.get("start_time").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `start_time` to be a primitive type in the JSON string but got `%s`", jsonObj.get("start_time").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ServiceContainer.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ServiceContainer' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ServiceContainer> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ServiceContainer.class));

       return (TypeAdapter<T>) new TypeAdapter<ServiceContainer>() {
           @Override
           public void write(JsonWriter out, ServiceContainer value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ServiceContainer read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ServiceContainer given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ServiceContainer
   * @throws IOException if the JSON string is invalid with respect to ServiceContainer
   */
  public static ServiceContainer fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ServiceContainer.class);
  }

  /**
   * Convert an instance of ServiceContainer to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}


