/*
 * Snowflake Services API
 * The Snowflake Services API is a REST API that you can use to access, update, and perform certain actions on Services resource in a Snowflake database.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import eu.openanalytics.containerproxy.backend.spcs.client.JSON;

/**
 * ServiceRoleGrantTo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-06T17:47:48.337179400+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
public class ServiceRoleGrantTo {
  public static final String SERIALIZED_NAME_CREATED_ON = "created_on";
  @SerializedName(SERIALIZED_NAME_CREATED_ON)
  @javax.annotation.Nullable
  private OffsetDateTime createdOn;

  public static final String SERIALIZED_NAME_PRIVILEGE = "privilege";
  @SerializedName(SERIALIZED_NAME_PRIVILEGE)
  @javax.annotation.Nullable
  private String privilege;

  public static final String SERIALIZED_NAME_GRANTED_ON = "granted_on";
  @SerializedName(SERIALIZED_NAME_GRANTED_ON)
  @javax.annotation.Nullable
  private String grantedOn;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_GRANTED_TO = "granted_to";
  @SerializedName(SERIALIZED_NAME_GRANTED_TO)
  @javax.annotation.Nullable
  private String grantedTo;

  public static final String SERIALIZED_NAME_GRANTEE_NAME = "grantee_name";
  @SerializedName(SERIALIZED_NAME_GRANTEE_NAME)
  @javax.annotation.Nullable
  private String granteeName;

  public ServiceRoleGrantTo() {
  }

  public ServiceRoleGrantTo(
     OffsetDateTime createdOn, 
     String privilege, 
     String grantedOn, 
     String name, 
     String grantedTo, 
     String granteeName
  ) {
    this();
    this.createdOn = createdOn;
    this.privilege = privilege;
    this.grantedOn = grantedOn;
    this.name = name;
    this.grantedTo = grantedTo;
    this.granteeName = granteeName;
  }

  /**
   * Date and time when the grant was created
   * @return createdOn
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedOn() {
    return createdOn;
  }



  /**
   * The name of the privilege
   * @return privilege
   */
  @javax.annotation.Nullable
  public String getPrivilege() {
    return privilege;
  }



  /**
   * The type of of the securable
   * @return grantedOn
   */
  @javax.annotation.Nullable
  public String getGrantedOn() {
    return grantedOn;
  }



  /**
   * The name of the securable
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }



  /**
   * The type of the grantee
   * @return grantedTo
   */
  @javax.annotation.Nullable
  public String getGrantedTo() {
    return grantedTo;
  }



  /**
   * The name of the grantee
   * @return granteeName
   */
  @javax.annotation.Nullable
  public String getGranteeName() {
    return granteeName;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceRoleGrantTo serviceRoleGrantTo = (ServiceRoleGrantTo) o;
    return Objects.equals(this.createdOn, serviceRoleGrantTo.createdOn) &&
        Objects.equals(this.privilege, serviceRoleGrantTo.privilege) &&
        Objects.equals(this.grantedOn, serviceRoleGrantTo.grantedOn) &&
        Objects.equals(this.name, serviceRoleGrantTo.name) &&
        Objects.equals(this.grantedTo, serviceRoleGrantTo.grantedTo) &&
        Objects.equals(this.granteeName, serviceRoleGrantTo.granteeName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdOn, privilege, grantedOn, name, grantedTo, granteeName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceRoleGrantTo {\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    privilege: ").append(toIndentedString(privilege)).append("\n");
    sb.append("    grantedOn: ").append(toIndentedString(grantedOn)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    grantedTo: ").append(toIndentedString(grantedTo)).append("\n");
    sb.append("    granteeName: ").append(toIndentedString(granteeName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("created_on", "privilege", "granted_on", "name", "granted_to", "grantee_name"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ServiceRoleGrantTo
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ServiceRoleGrantTo.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in ServiceRoleGrantTo is not found in the empty JSON string", ServiceRoleGrantTo.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ServiceRoleGrantTo.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ServiceRoleGrantTo` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("privilege") != null && !jsonObj.get("privilege").isJsonNull()) && !jsonObj.get("privilege").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `privilege` to be a primitive type in the JSON string but got `%s`", jsonObj.get("privilege").toString()));
      }
      if ((jsonObj.get("granted_on") != null && !jsonObj.get("granted_on").isJsonNull()) && !jsonObj.get("granted_on").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `granted_on` to be a primitive type in the JSON string but got `%s`", jsonObj.get("granted_on").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("granted_to") != null && !jsonObj.get("granted_to").isJsonNull()) && !jsonObj.get("granted_to").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `granted_to` to be a primitive type in the JSON string but got `%s`", jsonObj.get("granted_to").toString()));
      }
      if ((jsonObj.get("grantee_name") != null && !jsonObj.get("grantee_name").isJsonNull()) && !jsonObj.get("grantee_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `grantee_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("grantee_name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ServiceRoleGrantTo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ServiceRoleGrantTo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ServiceRoleGrantTo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ServiceRoleGrantTo.class));

       return (TypeAdapter<T>) new TypeAdapter<ServiceRoleGrantTo>() {
           @Override
           public void write(JsonWriter out, ServiceRoleGrantTo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ServiceRoleGrantTo read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ServiceRoleGrantTo given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ServiceRoleGrantTo
   * @throws IOException if the JSON string is invalid with respect to ServiceRoleGrantTo
   */
  public static ServiceRoleGrantTo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ServiceRoleGrantTo.class);
  }

  /**
   * Convert an instance of ServiceRoleGrantTo to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}


