/*
 * Snowflake Services API
 * The Snowflake Services API is a REST API that you can use to access, update, and perform certain actions on Services resource in a Snowflake database.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Locale;
import eu.openanalytics.containerproxy.backend.spcs.client.model.ServiceSpec;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import eu.openanalytics.containerproxy.backend.spcs.client.JSON;

/**
 * ServiceSpecStageFile
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-06T17:47:48.337179400+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
public class ServiceSpecStageFile extends ServiceSpec {
  public static final String SERIALIZED_NAME_STAGE = "stage";
  @SerializedName(SERIALIZED_NAME_STAGE)
  @javax.annotation.Nonnull
  private String stage;

  public static final String SERIALIZED_NAME_SPEC_FILE = "spec_file";
  @SerializedName(SERIALIZED_NAME_SPEC_FILE)
  @javax.annotation.Nonnull
  private String specFile;

  public ServiceSpecStageFile() {
    this.specType = this.getClass().getSimpleName();
  }

  public ServiceSpecStageFile stage(@javax.annotation.Nonnull String stage) {
    this.stage = stage;
    return this;
  }

  /**
   * Specifies the Snowflake internal stage where the specification file is stored; for example, @tutorial_stage.
   * @return stage
   */
  @javax.annotation.Nonnull
  public String getStage() {
    return stage;
  }

  public void setStage(@javax.annotation.Nonnull String stage) {
    this.stage = stage;
  }


  public ServiceSpecStageFile specFile(@javax.annotation.Nonnull String specFile) {
    this.specFile = specFile;
    return this;
  }

  /**
   * Specifies the path to the service specification file on the stage; for example, &#39;some-dir/echo_spec.yaml&#39;.
   * @return specFile
   */
  @javax.annotation.Nonnull
  public String getSpecFile() {
    return specFile;
  }

  public void setSpecFile(@javax.annotation.Nonnull String specFile) {
    this.specFile = specFile;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceSpecStageFile serviceSpecStageFile = (ServiceSpecStageFile) o;
    return Objects.equals(this.stage, serviceSpecStageFile.stage) &&
        Objects.equals(this.specFile, serviceSpecStageFile.specFile) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stage, specFile, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceSpecStageFile {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    stage: ").append(toIndentedString(stage)).append("\n");
    sb.append("    specFile: ").append(toIndentedString(specFile)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("spec_type", "stage", "spec_file"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("stage", "spec_file"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ServiceSpecStageFile
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ServiceSpecStageFile.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in ServiceSpecStageFile is not found in the empty JSON string", ServiceSpecStageFile.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ServiceSpecStageFile.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ServiceSpecStageFile` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ServiceSpecStageFile.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ServiceSpecStageFile.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ServiceSpecStageFile' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ServiceSpecStageFile> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ServiceSpecStageFile.class));

       return (TypeAdapter<T>) new TypeAdapter<ServiceSpecStageFile>() {
           @Override
           public void write(JsonWriter out, ServiceSpecStageFile value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ServiceSpecStageFile read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ServiceSpecStageFile given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ServiceSpecStageFile
   * @throws IOException if the JSON string is invalid with respect to ServiceSpecStageFile
   */
  public static ServiceSpecStageFile fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ServiceSpecStageFile.class);
  }

  /**
   * Convert an instance of ServiceSpecStageFile to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}


