/*
 * Snowflake Services API
 * The Snowflake Services API is a REST API that you can use to access, update, and perform certain actions on Services resource in a Snowflake database.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Locale;
import eu.openanalytics.containerproxy.backend.spcs.client.model.ServiceSpec;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import eu.openanalytics.containerproxy.backend.spcs.client.JSON;

/**
 * Service
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-06T17:47:48.337179400+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
public class Service {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private String status;

  public static final String SERIALIZED_NAME_COMPUTE_POOL = "compute_pool";
  @SerializedName(SERIALIZED_NAME_COMPUTE_POOL)
  @javax.annotation.Nonnull
  private String computePool;

  public static final String SERIALIZED_NAME_SPEC = "spec";
  @SerializedName(SERIALIZED_NAME_SPEC)
  @javax.annotation.Nonnull
  private ServiceSpec spec;

  public static final String SERIALIZED_NAME_EXTERNAL_ACCESS_INTEGRATIONS = "external_access_integrations";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_ACCESS_INTEGRATIONS)
  @javax.annotation.Nullable
  private List<String> externalAccessIntegrations = new ArrayList<>();

  public static final String SERIALIZED_NAME_QUERY_WAREHOUSE = "query_warehouse";
  @SerializedName(SERIALIZED_NAME_QUERY_WAREHOUSE)
  @javax.annotation.Nullable
  private String queryWarehouse;

  public static final String SERIALIZED_NAME_COMMENT = "comment";
  @SerializedName(SERIALIZED_NAME_COMMENT)
  @javax.annotation.Nullable
  private String comment;

  public static final String SERIALIZED_NAME_IS_ASYNC_JOB = "is_async_job";
  @SerializedName(SERIALIZED_NAME_IS_ASYNC_JOB)
  @javax.annotation.Nullable
  private Boolean isAsyncJob;

  public static final String SERIALIZED_NAME_AUTO_RESUME = "auto_resume";
  @SerializedName(SERIALIZED_NAME_AUTO_RESUME)
  @javax.annotation.Nullable
  private Boolean autoResume;

  public static final String SERIALIZED_NAME_CURRENT_INSTANCES = "current_instances";
  @SerializedName(SERIALIZED_NAME_CURRENT_INSTANCES)
  @javax.annotation.Nullable
  private Integer currentInstances;

  public static final String SERIALIZED_NAME_TARGET_INSTANCES = "target_instances";
  @SerializedName(SERIALIZED_NAME_TARGET_INSTANCES)
  @javax.annotation.Nullable
  private Integer targetInstances;

  public static final String SERIALIZED_NAME_MIN_READY_INSTANCES = "min_ready_instances";
  @SerializedName(SERIALIZED_NAME_MIN_READY_INSTANCES)
  @javax.annotation.Nullable
  private Integer minReadyInstances;

  public static final String SERIALIZED_NAME_MIN_INSTANCES = "min_instances";
  @SerializedName(SERIALIZED_NAME_MIN_INSTANCES)
  @javax.annotation.Nullable
  private Integer minInstances;

  public static final String SERIALIZED_NAME_MAX_INSTANCES = "max_instances";
  @SerializedName(SERIALIZED_NAME_MAX_INSTANCES)
  @javax.annotation.Nullable
  private Integer maxInstances;

  public static final String SERIALIZED_NAME_DATABASE_NAME = "database_name";
  @SerializedName(SERIALIZED_NAME_DATABASE_NAME)
  @javax.annotation.Nullable
  private String databaseName;

  public static final String SERIALIZED_NAME_SCHEMA_NAME = "schema_name";
  @SerializedName(SERIALIZED_NAME_SCHEMA_NAME)
  @javax.annotation.Nullable
  private String schemaName;

  public static final String SERIALIZED_NAME_OWNER = "owner";
  @SerializedName(SERIALIZED_NAME_OWNER)
  @javax.annotation.Nullable
  private String owner;

  public static final String SERIALIZED_NAME_DNS_NAME = "dns_name";
  @SerializedName(SERIALIZED_NAME_DNS_NAME)
  @javax.annotation.Nullable
  private String dnsName;

  public static final String SERIALIZED_NAME_CREATED_ON = "created_on";
  @SerializedName(SERIALIZED_NAME_CREATED_ON)
  @javax.annotation.Nullable
  private OffsetDateTime createdOn;

  public static final String SERIALIZED_NAME_UPDATED_ON = "updated_on";
  @SerializedName(SERIALIZED_NAME_UPDATED_ON)
  @javax.annotation.Nullable
  private OffsetDateTime updatedOn;

  public static final String SERIALIZED_NAME_RESUMED_ON = "resumed_on";
  @SerializedName(SERIALIZED_NAME_RESUMED_ON)
  @javax.annotation.Nullable
  private OffsetDateTime resumedOn;

  public static final String SERIALIZED_NAME_SUSPENDED_ON = "suspended_on";
  @SerializedName(SERIALIZED_NAME_SUSPENDED_ON)
  @javax.annotation.Nullable
  private OffsetDateTime suspendedOn;

  public static final String SERIALIZED_NAME_AUTO_SUSPEND_SECS = "auto_suspend_secs";
  @SerializedName(SERIALIZED_NAME_AUTO_SUSPEND_SECS)
  @javax.annotation.Nullable
  private Long autoSuspendSecs;

  public static final String SERIALIZED_NAME_OWNER_ROLE_TYPE = "owner_role_type";
  @SerializedName(SERIALIZED_NAME_OWNER_ROLE_TYPE)
  @javax.annotation.Nullable
  private String ownerRoleType;

  public static final String SERIALIZED_NAME_IS_JOB = "is_job";
  @SerializedName(SERIALIZED_NAME_IS_JOB)
  @javax.annotation.Nullable
  private Boolean isJob;

  public static final String SERIALIZED_NAME_SPEC_DIGEST = "spec_digest";
  @SerializedName(SERIALIZED_NAME_SPEC_DIGEST)
  @javax.annotation.Nullable
  private String specDigest;

  public static final String SERIALIZED_NAME_IS_UPGRADING = "is_upgrading";
  @SerializedName(SERIALIZED_NAME_IS_UPGRADING)
  @javax.annotation.Nullable
  private Boolean isUpgrading;

  public static final String SERIALIZED_NAME_MANAGING_OBJECT_DOMAIN = "managing_object_domain";
  @SerializedName(SERIALIZED_NAME_MANAGING_OBJECT_DOMAIN)
  @javax.annotation.Nullable
  private String managingObjectDomain;

  public static final String SERIALIZED_NAME_MANAGING_OBJECT_NAME = "managing_object_name";
  @SerializedName(SERIALIZED_NAME_MANAGING_OBJECT_NAME)
  @javax.annotation.Nullable
  private String managingObjectName;

  public Service() {
  }

  public Service(
     Integer currentInstances, 
     Integer targetInstances, 
     String owner, 
     String dnsName, 
     OffsetDateTime createdOn, 
     OffsetDateTime updatedOn, 
     OffsetDateTime resumedOn, 
     OffsetDateTime suspendedOn, 
     String ownerRoleType, 
     Boolean isJob, 
     String specDigest, 
     Boolean isUpgrading, 
     String managingObjectDomain, 
     String managingObjectName
  ) {
    this();
    this.currentInstances = currentInstances;
    this.targetInstances = targetInstances;
    this.owner = owner;
    this.dnsName = dnsName;
    this.createdOn = createdOn;
    this.updatedOn = updatedOn;
    this.resumedOn = resumedOn;
    this.suspendedOn = suspendedOn;
    this.ownerRoleType = ownerRoleType;
    this.isJob = isJob;
    this.specDigest = specDigest;
    this.isUpgrading = isUpgrading;
    this.managingObjectDomain = managingObjectDomain;
    this.managingObjectName = managingObjectName;
  }

  public Service name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * A Snowflake object identifier. If the identifier contains spaces or special characters, the entire string must be enclosed in double quotes. Identifiers enclosed in double quotes are also case-sensitive.
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public Service status(@javax.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * The current status of the service.
   * @return status
   */
  @javax.annotation.Nullable
  public String getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }


  public Service computePool(@javax.annotation.Nonnull String computePool) {
    this.computePool = computePool;
    return this;
  }

  /**
   * Specifies the name of the compute pool in your account on which to run the service.
   * @return computePool
   */
  @javax.annotation.Nonnull
  public String getComputePool() {
    return computePool;
  }

  public void setComputePool(@javax.annotation.Nonnull String computePool) {
    this.computePool = computePool;
  }


  public Service spec(@javax.annotation.Nonnull ServiceSpec spec) {
    this.spec = spec;
    return this;
  }

  /**
   * Get spec
   * @return spec
   */
  @javax.annotation.Nonnull
  public ServiceSpec getSpec() {
    return spec;
  }

  public void setSpec(@javax.annotation.Nonnull ServiceSpec spec) {
    this.spec = spec;
  }


  public Service externalAccessIntegrations(@javax.annotation.Nullable List<String> externalAccessIntegrations) {
    this.externalAccessIntegrations = externalAccessIntegrations;
    return this;
  }

  public Service addExternalAccessIntegrationsItem(String externalAccessIntegrationsItem) {
    if (this.externalAccessIntegrations == null) {
      this.externalAccessIntegrations = new ArrayList<>();
    }
    this.externalAccessIntegrations.add(externalAccessIntegrationsItem);
    return this;
  }

  /**
   * Specifies the names of the external access integrations that allow your service to access external sites.
   * @return externalAccessIntegrations
   */
  @javax.annotation.Nullable
  public List<String> getExternalAccessIntegrations() {
    return externalAccessIntegrations;
  }

  public void setExternalAccessIntegrations(@javax.annotation.Nullable List<String> externalAccessIntegrations) {
    this.externalAccessIntegrations = externalAccessIntegrations;
  }


  public Service queryWarehouse(@javax.annotation.Nullable String queryWarehouse) {
    this.queryWarehouse = queryWarehouse;
    return this;
  }

  /**
   * A Snowflake object identifier. If the identifier contains spaces or special characters, the entire string must be enclosed in double quotes. Identifiers enclosed in double quotes are also case-sensitive.
   * @return queryWarehouse
   */
  @javax.annotation.Nullable
  public String getQueryWarehouse() {
    return queryWarehouse;
  }

  public void setQueryWarehouse(@javax.annotation.Nullable String queryWarehouse) {
    this.queryWarehouse = queryWarehouse;
  }


  public Service comment(@javax.annotation.Nullable String comment) {
    this.comment = comment;
    return this;
  }

  /**
   * Specifies a comment for the service.
   * @return comment
   */
  @javax.annotation.Nullable
  public String getComment() {
    return comment;
  }

  public void setComment(@javax.annotation.Nullable String comment) {
    this.comment = comment;
  }


  public Service isAsyncJob(@javax.annotation.Nullable Boolean isAsyncJob) {
    this.isAsyncJob = isAsyncJob;
    return this;
  }

  /**
   * True if the service is an async job service; false otherwise.
   * @return isAsyncJob
   */
  @javax.annotation.Nullable
  public Boolean getIsAsyncJob() {
    return isAsyncJob;
  }

  public void setIsAsyncJob(@javax.annotation.Nullable Boolean isAsyncJob) {
    this.isAsyncJob = isAsyncJob;
  }


  public Service autoResume(@javax.annotation.Nullable Boolean autoResume) {
    this.autoResume = autoResume;
    return this;
  }

  /**
   * Specifies whether to automatically resume a service when a service function or ingress is called.
   * @return autoResume
   */
  @javax.annotation.Nullable
  public Boolean getAutoResume() {
    return autoResume;
  }

  public void setAutoResume(@javax.annotation.Nullable Boolean autoResume) {
    this.autoResume = autoResume;
  }


  /**
   * The current number of instances for the service.
   * @return currentInstances
   */
  @javax.annotation.Nullable
  public Integer getCurrentInstances() {
    return currentInstances;
  }



  /**
   * The target number of service instances that should be running as determined by Snowflake.
   * @return targetInstances
   */
  @javax.annotation.Nullable
  public Integer getTargetInstances() {
    return targetInstances;
  }



  public Service minReadyInstances(@javax.annotation.Nullable Integer minReadyInstances) {
    this.minReadyInstances = minReadyInstances;
    return this;
  }

  /**
   * The minimum number of ready service instances to declare the service as READY.
   * @return minReadyInstances
   */
  @javax.annotation.Nullable
  public Integer getMinReadyInstances() {
    return minReadyInstances;
  }

  public void setMinReadyInstances(@javax.annotation.Nullable Integer minReadyInstances) {
    this.minReadyInstances = minReadyInstances;
  }


  public Service minInstances(@javax.annotation.Nullable Integer minInstances) {
    this.minInstances = minInstances;
    return this;
  }

  /**
   * Specifies the minimum number of service instances to run.
   * @return minInstances
   */
  @javax.annotation.Nullable
  public Integer getMinInstances() {
    return minInstances;
  }

  public void setMinInstances(@javax.annotation.Nullable Integer minInstances) {
    this.minInstances = minInstances;
  }


  public Service maxInstances(@javax.annotation.Nullable Integer maxInstances) {
    this.maxInstances = maxInstances;
    return this;
  }

  /**
   * Specifies the maximum number of service instances to run.
   * @return maxInstances
   */
  @javax.annotation.Nullable
  public Integer getMaxInstances() {
    return maxInstances;
  }

  public void setMaxInstances(@javax.annotation.Nullable Integer maxInstances) {
    this.maxInstances = maxInstances;
  }


  public Service databaseName(@javax.annotation.Nullable String databaseName) {
    this.databaseName = databaseName;
    return this;
  }

  /**
   * A Snowflake object identifier. If the identifier contains spaces or special characters, the entire string must be enclosed in double quotes. Identifiers enclosed in double quotes are also case-sensitive.
   * @return databaseName
   */
  @javax.annotation.Nullable
  public String getDatabaseName() {
    return databaseName;
  }

  public void setDatabaseName(@javax.annotation.Nullable String databaseName) {
    this.databaseName = databaseName;
  }


  public Service schemaName(@javax.annotation.Nullable String schemaName) {
    this.schemaName = schemaName;
    return this;
  }

  /**
   * A Snowflake object identifier. If the identifier contains spaces or special characters, the entire string must be enclosed in double quotes. Identifiers enclosed in double quotes are also case-sensitive.
   * @return schemaName
   */
  @javax.annotation.Nullable
  public String getSchemaName() {
    return schemaName;
  }

  public void setSchemaName(@javax.annotation.Nullable String schemaName) {
    this.schemaName = schemaName;
  }


  /**
   * Role that owns the service.
   * @return owner
   */
  @javax.annotation.Nullable
  public String getOwner() {
    return owner;
  }



  /**
   * Snowflake-assiged DNS name of the service. The DNS name enables service-to-service communications.
   * @return dnsName
   */
  @javax.annotation.Nullable
  public String getDnsName() {
    return dnsName;
  }



  /**
   * Timestamp when the service was created.
   * @return createdOn
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedOn() {
    return createdOn;
  }



  /**
   * Timestamp when the service was last updated.
   * @return updatedOn
   */
  @javax.annotation.Nullable
  public OffsetDateTime getUpdatedOn() {
    return updatedOn;
  }



  /**
   * Timestamp when the service was last resumed.
   * @return resumedOn
   */
  @javax.annotation.Nullable
  public OffsetDateTime getResumedOn() {
    return resumedOn;
  }



  /**
   * Timestamp when the service was last suspended.
   * @return suspendedOn
   */
  @javax.annotation.Nullable
  public OffsetDateTime getSuspendedOn() {
    return suspendedOn;
  }



  public Service autoSuspendSecs(@javax.annotation.Nullable Long autoSuspendSecs) {
    this.autoSuspendSecs = autoSuspendSecs;
    return this;
  }

  /**
   * Number of seconds of inactivity after which the service will be automatically suspended. The default value is 0 which represents the service will not be automatically suspended.
   * @return autoSuspendSecs
   */
  @javax.annotation.Nullable
  public Long getAutoSuspendSecs() {
    return autoSuspendSecs;
  }

  public void setAutoSuspendSecs(@javax.annotation.Nullable Long autoSuspendSecs) {
    this.autoSuspendSecs = autoSuspendSecs;
  }


  /**
   * The role type of the service owner.
   * @return ownerRoleType
   */
  @javax.annotation.Nullable
  public String getOwnerRoleType() {
    return ownerRoleType;
  }



  /**
   * True if the service is a job service; false otherwise.
   * @return isJob
   */
  @javax.annotation.Nullable
  public Boolean getIsJob() {
    return isJob;
  }



  /**
   * The unique and immutable identifier representing the service spec content.
   * @return specDigest
   */
  @javax.annotation.Nullable
  public String getSpecDigest() {
    return specDigest;
  }



  /**
   * TRUE, if Snowflake is in the process of upgrading the service.
   * @return isUpgrading
   */
  @javax.annotation.Nullable
  public Boolean getIsUpgrading() {
    return isUpgrading;
  }



  /**
   * The domain of the managing object (for example, the domain of the notebook that manages the service). NULL if the service is not managed by a Snowflake entity.
   * @return managingObjectDomain
   */
  @javax.annotation.Nullable
  public String getManagingObjectDomain() {
    return managingObjectDomain;
  }



  /**
   * The name of the managing object (for example, the name of the notebook that manages the service). NULL if the service is not managed by a Snowflake entity.
   * @return managingObjectName
   */
  @javax.annotation.Nullable
  public String getManagingObjectName() {
    return managingObjectName;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Service service = (Service) o;
    return Objects.equals(this.name, service.name) &&
        Objects.equals(this.status, service.status) &&
        Objects.equals(this.computePool, service.computePool) &&
        Objects.equals(this.spec, service.spec) &&
        Objects.equals(this.externalAccessIntegrations, service.externalAccessIntegrations) &&
        Objects.equals(this.queryWarehouse, service.queryWarehouse) &&
        Objects.equals(this.comment, service.comment) &&
        Objects.equals(this.isAsyncJob, service.isAsyncJob) &&
        Objects.equals(this.autoResume, service.autoResume) &&
        Objects.equals(this.currentInstances, service.currentInstances) &&
        Objects.equals(this.targetInstances, service.targetInstances) &&
        Objects.equals(this.minReadyInstances, service.minReadyInstances) &&
        Objects.equals(this.minInstances, service.minInstances) &&
        Objects.equals(this.maxInstances, service.maxInstances) &&
        Objects.equals(this.databaseName, service.databaseName) &&
        Objects.equals(this.schemaName, service.schemaName) &&
        Objects.equals(this.owner, service.owner) &&
        Objects.equals(this.dnsName, service.dnsName) &&
        Objects.equals(this.createdOn, service.createdOn) &&
        Objects.equals(this.updatedOn, service.updatedOn) &&
        Objects.equals(this.resumedOn, service.resumedOn) &&
        Objects.equals(this.suspendedOn, service.suspendedOn) &&
        Objects.equals(this.autoSuspendSecs, service.autoSuspendSecs) &&
        Objects.equals(this.ownerRoleType, service.ownerRoleType) &&
        Objects.equals(this.isJob, service.isJob) &&
        Objects.equals(this.specDigest, service.specDigest) &&
        Objects.equals(this.isUpgrading, service.isUpgrading) &&
        Objects.equals(this.managingObjectDomain, service.managingObjectDomain) &&
        Objects.equals(this.managingObjectName, service.managingObjectName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, status, computePool, spec, externalAccessIntegrations, queryWarehouse, comment, isAsyncJob, autoResume, currentInstances, targetInstances, minReadyInstances, minInstances, maxInstances, databaseName, schemaName, owner, dnsName, createdOn, updatedOn, resumedOn, suspendedOn, autoSuspendSecs, ownerRoleType, isJob, specDigest, isUpgrading, managingObjectDomain, managingObjectName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Service {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    computePool: ").append(toIndentedString(computePool)).append("\n");
    sb.append("    spec: ").append(toIndentedString(spec)).append("\n");
    sb.append("    externalAccessIntegrations: ").append(toIndentedString(externalAccessIntegrations)).append("\n");
    sb.append("    queryWarehouse: ").append(toIndentedString(queryWarehouse)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    isAsyncJob: ").append(toIndentedString(isAsyncJob)).append("\n");
    sb.append("    autoResume: ").append(toIndentedString(autoResume)).append("\n");
    sb.append("    currentInstances: ").append(toIndentedString(currentInstances)).append("\n");
    sb.append("    targetInstances: ").append(toIndentedString(targetInstances)).append("\n");
    sb.append("    minReadyInstances: ").append(toIndentedString(minReadyInstances)).append("\n");
    sb.append("    minInstances: ").append(toIndentedString(minInstances)).append("\n");
    sb.append("    maxInstances: ").append(toIndentedString(maxInstances)).append("\n");
    sb.append("    databaseName: ").append(toIndentedString(databaseName)).append("\n");
    sb.append("    schemaName: ").append(toIndentedString(schemaName)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    dnsName: ").append(toIndentedString(dnsName)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    updatedOn: ").append(toIndentedString(updatedOn)).append("\n");
    sb.append("    resumedOn: ").append(toIndentedString(resumedOn)).append("\n");
    sb.append("    suspendedOn: ").append(toIndentedString(suspendedOn)).append("\n");
    sb.append("    autoSuspendSecs: ").append(toIndentedString(autoSuspendSecs)).append("\n");
    sb.append("    ownerRoleType: ").append(toIndentedString(ownerRoleType)).append("\n");
    sb.append("    isJob: ").append(toIndentedString(isJob)).append("\n");
    sb.append("    specDigest: ").append(toIndentedString(specDigest)).append("\n");
    sb.append("    isUpgrading: ").append(toIndentedString(isUpgrading)).append("\n");
    sb.append("    managingObjectDomain: ").append(toIndentedString(managingObjectDomain)).append("\n");
    sb.append("    managingObjectName: ").append(toIndentedString(managingObjectName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("name", "status", "compute_pool", "spec", "external_access_integrations", "query_warehouse", "comment", "is_async_job", "auto_resume", "current_instances", "target_instances", "min_ready_instances", "min_instances", "max_instances", "database_name", "schema_name", "owner", "dns_name", "created_on", "updated_on", "resumed_on", "suspended_on", "auto_suspend_secs", "owner_role_type", "is_job", "spec_digest", "is_upgrading", "managing_object_domain", "managing_object_name"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("name", "compute_pool", "spec"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Service
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Service.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in Service is not found in the empty JSON string", Service.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Service.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Service` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Service.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if (!jsonObj.get("compute_pool").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `compute_pool` to be a primitive type in the JSON string but got `%s`", jsonObj.get("compute_pool").toString()));
      }
      // validate the required field `spec`
      ServiceSpec.validateJsonElement(jsonObj.get("spec"));
      // ensure the optional json data is an array if present
      if (jsonObj.get("external_access_integrations") != null && !jsonObj.get("external_access_integrations").isJsonNull() && !jsonObj.get("external_access_integrations").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `external_access_integrations` to be an array in the JSON string but got `%s`", jsonObj.get("external_access_integrations").toString()));
      }
      if ((jsonObj.get("query_warehouse") != null && !jsonObj.get("query_warehouse").isJsonNull()) && !jsonObj.get("query_warehouse").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `query_warehouse` to be a primitive type in the JSON string but got `%s`", jsonObj.get("query_warehouse").toString()));
      }
      if ((jsonObj.get("comment") != null && !jsonObj.get("comment").isJsonNull()) && !jsonObj.get("comment").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `comment` to be a primitive type in the JSON string but got `%s`", jsonObj.get("comment").toString()));
      }
      if ((jsonObj.get("database_name") != null && !jsonObj.get("database_name").isJsonNull()) && !jsonObj.get("database_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `database_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("database_name").toString()));
      }
      if ((jsonObj.get("schema_name") != null && !jsonObj.get("schema_name").isJsonNull()) && !jsonObj.get("schema_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `schema_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("schema_name").toString()));
      }
      if ((jsonObj.get("owner") != null && !jsonObj.get("owner").isJsonNull()) && !jsonObj.get("owner").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `owner` to be a primitive type in the JSON string but got `%s`", jsonObj.get("owner").toString()));
      }
      if ((jsonObj.get("dns_name") != null && !jsonObj.get("dns_name").isJsonNull()) && !jsonObj.get("dns_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `dns_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dns_name").toString()));
      }
      if ((jsonObj.get("owner_role_type") != null && !jsonObj.get("owner_role_type").isJsonNull()) && !jsonObj.get("owner_role_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `owner_role_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("owner_role_type").toString()));
      }
      if ((jsonObj.get("spec_digest") != null && !jsonObj.get("spec_digest").isJsonNull()) && !jsonObj.get("spec_digest").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `spec_digest` to be a primitive type in the JSON string but got `%s`", jsonObj.get("spec_digest").toString()));
      }
      if ((jsonObj.get("managing_object_domain") != null && !jsonObj.get("managing_object_domain").isJsonNull()) && !jsonObj.get("managing_object_domain").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `managing_object_domain` to be a primitive type in the JSON string but got `%s`", jsonObj.get("managing_object_domain").toString()));
      }
      if ((jsonObj.get("managing_object_name") != null && !jsonObj.get("managing_object_name").isJsonNull()) && !jsonObj.get("managing_object_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `managing_object_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("managing_object_name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Service.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Service' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Service> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Service.class));

       return (TypeAdapter<T>) new TypeAdapter<Service>() {
           @Override
           public void write(JsonWriter out, Service value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Service read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Service given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Service
   * @throws IOException if the JSON string is invalid with respect to Service
   */
  public static Service fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Service.class);
  }

  /**
   * Convert an instance of Service to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}


