/*
 * Snowflake Services API
 * The Snowflake Services API is a REST API that you can use to access, update, and perform certain actions on Services resource in a Snowflake database.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Locale;
import eu.openanalytics.containerproxy.backend.spcs.client.model.ServiceSpec;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import eu.openanalytics.containerproxy.backend.spcs.client.JSON;

/**
 * ServiceSpecInlineText
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-06T17:47:48.337179400+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
public class ServiceSpecInlineText extends ServiceSpec {
  public static final String SERIALIZED_NAME_SPEC_TEXT = "spec_text";
  @SerializedName(SERIALIZED_NAME_SPEC_TEXT)
  @javax.annotation.Nonnull
  private String specText;

  public ServiceSpecInlineText() {
    this.specType = this.getClass().getSimpleName();
  }

  public ServiceSpecInlineText specText(@javax.annotation.Nonnull String specText) {
    this.specText = specText;
    return this;
  }

  /**
   * Specifies service specification. You can use a pair of dollar signs ($$) to delimit the beginning and ending of the specification string.
   * @return specText
   */
  @javax.annotation.Nonnull
  public String getSpecText() {
    return specText;
  }

  public void setSpecText(@javax.annotation.Nonnull String specText) {
    this.specText = specText;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceSpecInlineText serviceSpecInlineText = (ServiceSpecInlineText) o;
    return Objects.equals(this.specText, serviceSpecInlineText.specText) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(specText, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceSpecInlineText {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    specText: ").append(toIndentedString(specText)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("spec_type", "spec_text"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("spec_text"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ServiceSpecInlineText
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ServiceSpecInlineText.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in ServiceSpecInlineText is not found in the empty JSON string", ServiceSpecInlineText.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ServiceSpecInlineText.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ServiceSpecInlineText` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ServiceSpecInlineText.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ServiceSpecInlineText.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ServiceSpecInlineText' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ServiceSpecInlineText> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ServiceSpecInlineText.class));

       return (TypeAdapter<T>) new TypeAdapter<ServiceSpecInlineText>() {
           @Override
           public void write(JsonWriter out, ServiceSpecInlineText value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ServiceSpecInlineText read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ServiceSpecInlineText given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ServiceSpecInlineText
   * @throws IOException if the JSON string is invalid with respect to ServiceSpecInlineText
   */
  public static ServiceSpecInlineText fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ServiceSpecInlineText.class);
  }

  /**
   * Convert an instance of ServiceSpecInlineText to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}


