/*
 * Snowflake Services API
 * The Snowflake Services API is a REST API that you can use to access, update, and perform certain actions on Services resource in a Snowflake database.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import eu.openanalytics.containerproxy.backend.spcs.client.JSON;

/**
 * Specifies service specification.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-06T17:47:48.337179400+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
public class ServiceSpec {
  public static final String SERIALIZED_NAME_SPEC_TYPE = "spec_type";
  @SerializedName(SERIALIZED_NAME_SPEC_TYPE)
  @javax.annotation.Nullable
  protected String specType;

  public ServiceSpec() {
    this.specType = this.getClass().getSimpleName();
  }

  public ServiceSpec specType(@javax.annotation.Nullable String specType) {
    this.specType = specType;
    return this;
  }

  /**
   * Type of the service specification, can be &#x60;from_file&#x60; or &#x60;from_inline&#x60;.
   * @return specType
   */
  @javax.annotation.Nullable
  public String getSpecType() {
    return specType;
  }

  public void setSpecType(@javax.annotation.Nullable String specType) {
    this.specType = specType;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceSpec serviceSpec = (ServiceSpec) o;
    return Objects.equals(this.specType, serviceSpec.specType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(specType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceSpec {\n");
    sb.append("    specType: ").append(toIndentedString(specType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("spec_type"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ServiceSpec
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ServiceSpec.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in ServiceSpec is not found in the empty JSON string", ServiceSpec.openapiRequiredFields.toString()));
        }
      }

      String discriminatorValue = jsonElement.getAsJsonObject().get("spec_type").getAsString();
      switch (discriminatorValue) {
        case "from_file":
          ServiceSpecStageFile.validateJsonElement(jsonElement);
          break;
        case "from_inline":
          ServiceSpecInlineText.validateJsonElement(jsonElement);
          break;
        default:
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The value of the `spec_type` field `%s` does not match any key defined in the discriminator's mapping.", discriminatorValue));
      }
  }


  /**
   * Create an instance of ServiceSpec given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ServiceSpec
   * @throws IOException if the JSON string is invalid with respect to ServiceSpec
   */
  public static ServiceSpec fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ServiceSpec.class);
  }

  /**
   * Convert an instance of ServiceSpec to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ServiceSpec.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ServiceSpec' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);

       return (TypeAdapter<T>) new TypeAdapter<ServiceSpec>() {
           @Override
           public void write(JsonWriter out, ServiceSpec value) throws IOException {
             // Use the appropriate adapter based on the actual type
             // Use getDelegateAdapter to skip this factory to avoid infinite recursion
             if (value instanceof ServiceSpecInlineText) {
               TypeAdapter<ServiceSpecInlineText> adapter = gson.getDelegateAdapter(CustomTypeAdapterFactory.this, TypeToken.get(ServiceSpecInlineText.class));
               adapter.write(out, (ServiceSpecInlineText) value);
             } else if (value instanceof ServiceSpecStageFile) {
               TypeAdapter<ServiceSpecStageFile> adapter = gson.getDelegateAdapter(CustomTypeAdapterFactory.this, TypeToken.get(ServiceSpecStageFile.class));
               adapter.write(out, (ServiceSpecStageFile) value);
             } else {
               // Fallback to base class
               TypeAdapter<ServiceSpec> adapter = gson.getDelegateAdapter(CustomTypeAdapterFactory.this, TypeToken.get(ServiceSpec.class));
               adapter.write(out, value);
             }
           }

           @Override
           public ServiceSpec read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             if (jsonElement == null || !jsonElement.isJsonObject()) {
               return null;
             }
             
             // Read discriminator value to determine which subclass to deserialize into
             JsonObject jsonObject = jsonElement.getAsJsonObject();
             JsonElement specTypeElement = jsonObject.get("spec_type");
             if (specTypeElement == null || specTypeElement.isJsonNull()) {
               throw new JsonParseException("Missing discriminator field 'spec_type' in ServiceSpec JSON");
             }
             
             String specType = specTypeElement.getAsString();
             
             // Deserialize into the appropriate subclass based on discriminator
             // Use getDelegateAdapter to skip this factory to avoid infinite recursion
             switch (specType) {
               case "from_inline":
                 TypeAdapter<ServiceSpecInlineText> inlineAdapter = gson.getDelegateAdapter(CustomTypeAdapterFactory.this, TypeToken.get(ServiceSpecInlineText.class));
                 return inlineAdapter.fromJsonTree(jsonElement);
               case "from_file":
                 TypeAdapter<ServiceSpecStageFile> stageFileAdapter = gson.getDelegateAdapter(CustomTypeAdapterFactory.this, TypeToken.get(ServiceSpecStageFile.class));
                 return stageFileAdapter.fromJsonTree(jsonElement);
               default:
                 throw new JsonParseException("Unknown discriminator value '" + specType + "' for ServiceSpec");
             }
           }

       }.nullSafe();
    }
  }
}


