/*
 * Snowflake SQL API
 * The Snowflake SQL API is a REST API that you can use to access and update data in a Snowflake database. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import eu.openanalytics.containerproxy.backend.spcs.client.JSON;

/**
 * Session parameters that should be set before executing the statement.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-06T17:47:56.670263400+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
public class SubmitStatementRequestParameters {
  public static final String SERIALIZED_NAME_TIMEZONE = "timezone";
  @SerializedName(SERIALIZED_NAME_TIMEZONE)
  @javax.annotation.Nullable
  private String timezone;

  public static final String SERIALIZED_NAME_QUERY_TAG = "query_tag";
  @SerializedName(SERIALIZED_NAME_QUERY_TAG)
  @javax.annotation.Nullable
  private String queryTag;

  public static final String SERIALIZED_NAME_BINARY_OUTPUT_FORMAT = "binary_output_format";
  @SerializedName(SERIALIZED_NAME_BINARY_OUTPUT_FORMAT)
  @javax.annotation.Nullable
  private String binaryOutputFormat;

  public static final String SERIALIZED_NAME_DATE_OUTPUT_FORMAT = "date_output_format";
  @SerializedName(SERIALIZED_NAME_DATE_OUTPUT_FORMAT)
  @javax.annotation.Nullable
  private String dateOutputFormat;

  public static final String SERIALIZED_NAME_TIME_OUTPUT_FORMAT = "time_output_format";
  @SerializedName(SERIALIZED_NAME_TIME_OUTPUT_FORMAT)
  @javax.annotation.Nullable
  private String timeOutputFormat;

  public static final String SERIALIZED_NAME_TIMESTAMP_OUTPUT_FORMAT = "timestamp_output_format";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP_OUTPUT_FORMAT)
  @javax.annotation.Nullable
  private String timestampOutputFormat;

  public static final String SERIALIZED_NAME_TIMESTAMP_LTZ_OUTPUT_FORMAT = "timestamp_ltz_output_format";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP_LTZ_OUTPUT_FORMAT)
  @javax.annotation.Nullable
  private String timestampLtzOutputFormat;

  public static final String SERIALIZED_NAME_TIMESTAMP_NTZ_OUTPUT_FORMAT = "timestamp_ntz_output_format";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP_NTZ_OUTPUT_FORMAT)
  @javax.annotation.Nullable
  private String timestampNtzOutputFormat;

  public static final String SERIALIZED_NAME_TIMESTAMP_TZ_OUTPUT_FORMAT = "timestamp_tz_output_format";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP_TZ_OUTPUT_FORMAT)
  @javax.annotation.Nullable
  private String timestampTzOutputFormat;

  public static final String SERIALIZED_NAME_MULTI_STATEMENT_COUNT = "multi_statement_count";
  @SerializedName(SERIALIZED_NAME_MULTI_STATEMENT_COUNT)
  @javax.annotation.Nullable
  private Integer multiStatementCount = 1;

  public SubmitStatementRequestParameters() {
  }

  public SubmitStatementRequestParameters timezone(@javax.annotation.Nullable String timezone) {
    this.timezone = timezone;
    return this;
  }

  /**
   * Time zone to use when executing the statement.
   * @return timezone
   */
  @javax.annotation.Nullable
  public String getTimezone() {
    return timezone;
  }

  public void setTimezone(@javax.annotation.Nullable String timezone) {
    this.timezone = timezone;
  }


  public SubmitStatementRequestParameters queryTag(@javax.annotation.Nullable String queryTag) {
    this.queryTag = queryTag;
    return this;
  }

  /**
   * Query tag that you want to associate with the SQL statement.
   * @return queryTag
   */
  @javax.annotation.Nullable
  public String getQueryTag() {
    return queryTag;
  }

  public void setQueryTag(@javax.annotation.Nullable String queryTag) {
    this.queryTag = queryTag;
  }


  public SubmitStatementRequestParameters binaryOutputFormat(@javax.annotation.Nullable String binaryOutputFormat) {
    this.binaryOutputFormat = binaryOutputFormat;
    return this;
  }

  /**
   * Output format for binary values.
   * @return binaryOutputFormat
   */
  @javax.annotation.Nullable
  public String getBinaryOutputFormat() {
    return binaryOutputFormat;
  }

  public void setBinaryOutputFormat(@javax.annotation.Nullable String binaryOutputFormat) {
    this.binaryOutputFormat = binaryOutputFormat;
  }


  public SubmitStatementRequestParameters dateOutputFormat(@javax.annotation.Nullable String dateOutputFormat) {
    this.dateOutputFormat = dateOutputFormat;
    return this;
  }

  /**
   * Output format for DATE values.
   * @return dateOutputFormat
   */
  @javax.annotation.Nullable
  public String getDateOutputFormat() {
    return dateOutputFormat;
  }

  public void setDateOutputFormat(@javax.annotation.Nullable String dateOutputFormat) {
    this.dateOutputFormat = dateOutputFormat;
  }


  public SubmitStatementRequestParameters timeOutputFormat(@javax.annotation.Nullable String timeOutputFormat) {
    this.timeOutputFormat = timeOutputFormat;
    return this;
  }

  /**
   * Output format for TIME values.
   * @return timeOutputFormat
   */
  @javax.annotation.Nullable
  public String getTimeOutputFormat() {
    return timeOutputFormat;
  }

  public void setTimeOutputFormat(@javax.annotation.Nullable String timeOutputFormat) {
    this.timeOutputFormat = timeOutputFormat;
  }


  public SubmitStatementRequestParameters timestampOutputFormat(@javax.annotation.Nullable String timestampOutputFormat) {
    this.timestampOutputFormat = timestampOutputFormat;
    return this;
  }

  /**
   * Output format for TIMESTAMP values.
   * @return timestampOutputFormat
   */
  @javax.annotation.Nullable
  public String getTimestampOutputFormat() {
    return timestampOutputFormat;
  }

  public void setTimestampOutputFormat(@javax.annotation.Nullable String timestampOutputFormat) {
    this.timestampOutputFormat = timestampOutputFormat;
  }


  public SubmitStatementRequestParameters timestampLtzOutputFormat(@javax.annotation.Nullable String timestampLtzOutputFormat) {
    this.timestampLtzOutputFormat = timestampLtzOutputFormat;
    return this;
  }

  /**
   * Output format for TIMESTAMP_LTZ values.
   * @return timestampLtzOutputFormat
   */
  @javax.annotation.Nullable
  public String getTimestampLtzOutputFormat() {
    return timestampLtzOutputFormat;
  }

  public void setTimestampLtzOutputFormat(@javax.annotation.Nullable String timestampLtzOutputFormat) {
    this.timestampLtzOutputFormat = timestampLtzOutputFormat;
  }


  public SubmitStatementRequestParameters timestampNtzOutputFormat(@javax.annotation.Nullable String timestampNtzOutputFormat) {
    this.timestampNtzOutputFormat = timestampNtzOutputFormat;
    return this;
  }

  /**
   * Output format for TIMESTAMP_NTZ values.
   * @return timestampNtzOutputFormat
   */
  @javax.annotation.Nullable
  public String getTimestampNtzOutputFormat() {
    return timestampNtzOutputFormat;
  }

  public void setTimestampNtzOutputFormat(@javax.annotation.Nullable String timestampNtzOutputFormat) {
    this.timestampNtzOutputFormat = timestampNtzOutputFormat;
  }


  public SubmitStatementRequestParameters timestampTzOutputFormat(@javax.annotation.Nullable String timestampTzOutputFormat) {
    this.timestampTzOutputFormat = timestampTzOutputFormat;
    return this;
  }

  /**
   * Output format for TIMESTAMP_TZ values.
   * @return timestampTzOutputFormat
   */
  @javax.annotation.Nullable
  public String getTimestampTzOutputFormat() {
    return timestampTzOutputFormat;
  }

  public void setTimestampTzOutputFormat(@javax.annotation.Nullable String timestampTzOutputFormat) {
    this.timestampTzOutputFormat = timestampTzOutputFormat;
  }


  public SubmitStatementRequestParameters multiStatementCount(@javax.annotation.Nullable Integer multiStatementCount) {
    this.multiStatementCount = multiStatementCount;
    return this;
  }

  /**
   * Number of statements to execute when using multi-statement capability. 0 implies variable number of statements. Negative numbers are not allowed.
   * @return multiStatementCount
   */
  @javax.annotation.Nullable
  public Integer getMultiStatementCount() {
    return multiStatementCount;
  }

  public void setMultiStatementCount(@javax.annotation.Nullable Integer multiStatementCount) {
    this.multiStatementCount = multiStatementCount;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubmitStatementRequestParameters submitStatementRequestParameters = (SubmitStatementRequestParameters) o;
    return Objects.equals(this.timezone, submitStatementRequestParameters.timezone) &&
        Objects.equals(this.queryTag, submitStatementRequestParameters.queryTag) &&
        Objects.equals(this.binaryOutputFormat, submitStatementRequestParameters.binaryOutputFormat) &&
        Objects.equals(this.dateOutputFormat, submitStatementRequestParameters.dateOutputFormat) &&
        Objects.equals(this.timeOutputFormat, submitStatementRequestParameters.timeOutputFormat) &&
        Objects.equals(this.timestampOutputFormat, submitStatementRequestParameters.timestampOutputFormat) &&
        Objects.equals(this.timestampLtzOutputFormat, submitStatementRequestParameters.timestampLtzOutputFormat) &&
        Objects.equals(this.timestampNtzOutputFormat, submitStatementRequestParameters.timestampNtzOutputFormat) &&
        Objects.equals(this.timestampTzOutputFormat, submitStatementRequestParameters.timestampTzOutputFormat) &&
        Objects.equals(this.multiStatementCount, submitStatementRequestParameters.multiStatementCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timezone, queryTag, binaryOutputFormat, dateOutputFormat, timeOutputFormat, timestampOutputFormat, timestampLtzOutputFormat, timestampNtzOutputFormat, timestampTzOutputFormat, multiStatementCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubmitStatementRequestParameters {\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    queryTag: ").append(toIndentedString(queryTag)).append("\n");
    sb.append("    binaryOutputFormat: ").append(toIndentedString(binaryOutputFormat)).append("\n");
    sb.append("    dateOutputFormat: ").append(toIndentedString(dateOutputFormat)).append("\n");
    sb.append("    timeOutputFormat: ").append(toIndentedString(timeOutputFormat)).append("\n");
    sb.append("    timestampOutputFormat: ").append(toIndentedString(timestampOutputFormat)).append("\n");
    sb.append("    timestampLtzOutputFormat: ").append(toIndentedString(timestampLtzOutputFormat)).append("\n");
    sb.append("    timestampNtzOutputFormat: ").append(toIndentedString(timestampNtzOutputFormat)).append("\n");
    sb.append("    timestampTzOutputFormat: ").append(toIndentedString(timestampTzOutputFormat)).append("\n");
    sb.append("    multiStatementCount: ").append(toIndentedString(multiStatementCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("timezone", "query_tag", "binary_output_format", "date_output_format", "time_output_format", "timestamp_output_format", "timestamp_ltz_output_format", "timestamp_ntz_output_format", "timestamp_tz_output_format", "multi_statement_count"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SubmitStatementRequestParameters
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SubmitStatementRequestParameters.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in SubmitStatementRequestParameters is not found in the empty JSON string", SubmitStatementRequestParameters.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SubmitStatementRequestParameters.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `SubmitStatementRequestParameters` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("timezone") != null && !jsonObj.get("timezone").isJsonNull()) && !jsonObj.get("timezone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `timezone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timezone").toString()));
      }
      if ((jsonObj.get("query_tag") != null && !jsonObj.get("query_tag").isJsonNull()) && !jsonObj.get("query_tag").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `query_tag` to be a primitive type in the JSON string but got `%s`", jsonObj.get("query_tag").toString()));
      }
      if ((jsonObj.get("binary_output_format") != null && !jsonObj.get("binary_output_format").isJsonNull()) && !jsonObj.get("binary_output_format").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `binary_output_format` to be a primitive type in the JSON string but got `%s`", jsonObj.get("binary_output_format").toString()));
      }
      if ((jsonObj.get("date_output_format") != null && !jsonObj.get("date_output_format").isJsonNull()) && !jsonObj.get("date_output_format").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `date_output_format` to be a primitive type in the JSON string but got `%s`", jsonObj.get("date_output_format").toString()));
      }
      if ((jsonObj.get("time_output_format") != null && !jsonObj.get("time_output_format").isJsonNull()) && !jsonObj.get("time_output_format").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `time_output_format` to be a primitive type in the JSON string but got `%s`", jsonObj.get("time_output_format").toString()));
      }
      if ((jsonObj.get("timestamp_output_format") != null && !jsonObj.get("timestamp_output_format").isJsonNull()) && !jsonObj.get("timestamp_output_format").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `timestamp_output_format` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timestamp_output_format").toString()));
      }
      if ((jsonObj.get("timestamp_ltz_output_format") != null && !jsonObj.get("timestamp_ltz_output_format").isJsonNull()) && !jsonObj.get("timestamp_ltz_output_format").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `timestamp_ltz_output_format` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timestamp_ltz_output_format").toString()));
      }
      if ((jsonObj.get("timestamp_ntz_output_format") != null && !jsonObj.get("timestamp_ntz_output_format").isJsonNull()) && !jsonObj.get("timestamp_ntz_output_format").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `timestamp_ntz_output_format` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timestamp_ntz_output_format").toString()));
      }
      if ((jsonObj.get("timestamp_tz_output_format") != null && !jsonObj.get("timestamp_tz_output_format").isJsonNull()) && !jsonObj.get("timestamp_tz_output_format").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `timestamp_tz_output_format` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timestamp_tz_output_format").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SubmitStatementRequestParameters.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SubmitStatementRequestParameters' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SubmitStatementRequestParameters> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SubmitStatementRequestParameters.class));

       return (TypeAdapter<T>) new TypeAdapter<SubmitStatementRequestParameters>() {
           @Override
           public void write(JsonWriter out, SubmitStatementRequestParameters value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SubmitStatementRequestParameters read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SubmitStatementRequestParameters given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SubmitStatementRequestParameters
   * @throws IOException if the JSON string is invalid with respect to SubmitStatementRequestParameters
   */
  public static SubmitStatementRequestParameters fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SubmitStatementRequestParameters.class);
  }

  /**
   * Convert an instance of SubmitStatementRequestParameters to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

